packages/website/package.json
packages/website/src/helpers/mapBounds.ts
packages/website/src/routes/ReefRoutes/Reef/FeatureVideo/__snapshots__/index.test.tsx.snap
packages/website/src/routes/ReefRoutes/Reef/FeatureVideo/index.test.tsx
packages/website/src/routes/ReefRoutes/Reef/FeatureVideo/index.tsx
packages/website/src/routes/ReefRoutes/Reef/Map/__snapshots__/index.test.tsx.snap
packages/website/src/routes/ReefRoutes/Reef/Map/index.test.tsx
packages/website/src/routes/ReefRoutes/Reef/Map/index.tsx
packages/website/src/routes/ReefRoutes/Reef/__snapshots__/index.test.tsx.snap
packages/website/src/routes/ReefRoutes/Reef/index.test.tsx
packages/website/src/routes/ReefRoutes/Reef/index.tsx
packages/website/src/store/Reefs/slice.ts
packages/website/src/store/Reefs/types.ts
yarn.lock

This pull request concerns the feature video on the reef detail page. Here's a screenshot of what it looks like.

Add featured video to the reef detail page

---

packages/application/src/Form/index.tsx

🎨 Update the form mobile version

---

packages/website/.firebaserc
packages/website/.gitignore
packages/website/firebase.json
packages/website/package.json
yarn.lock

Add firebase deployment info for the webapp

---

packages/api/src/reefs/dto/create-reef.dto.ts
packages/api/src/reefs/dto/filter-reef.dto.ts
packages/api/src/reefs/dto/update-reef.dto.ts
packages/api/src/reefs/reefs.controller.spec.ts
packages/api/src/reefs/reefs.controller.ts
packages/api/src/reefs/reefs.entity.ts
packages/api/src/reefs/reefs.module.ts
packages/api/src/reefs/reefs.service.ts
packages/api/src/regions/regions.controller.ts
packages/api/src/regions/regions.service.ts

This PR adds CRUD endpoints for reefs.

Add CRUD endpoints for reefs

---

packages/api/migration/1594204305108-RemoveVarcharLimit.ts
packages/api/src/reef-applications/reef-applications.entity.ts
packages/api/src/reef-pois/reef-pois.entity.ts
packages/api/src/reefs/video-streams.entity.ts
packages/api/src/regions/regions.entity.ts
packages/api/src/spotters/spotters.entity.ts
packages/api/src/users/users.entity.ts

This PR removes the length limits from `varchar` fields.

Remove length limit from varchar fields

---

packages/api/tsconfig.json

Add include 'src' to the api tsconfig.json

Fix API build

---

packages/website/src/helpers/numberUtils.ts
packages/website/src/routes/Homepage/ReefTable/SelectedReefCard/__snapshots__/index.test.tsx.snap
packages/website/src/routes/Homepage/ReefTable/SelectedReefCard/index.tsx
packages/website/src/routes/Homepage/index.tsx
packages/website/src/routes/ReefRoutes/Reef/Charts/Tooltip/index.tsx
packages/website/src/routes/ReefRoutes/Reef/Charts/__snapshots__/index.test.tsx.snap
packages/website/src/routes/ReefRoutes/Reef/Charts/index.tsx
packages/website/src/routes/ReefRoutes/Reef/Charts/utils.ts
packages/website/src/routes/ReefRoutes/Reef/ReefDetails.tsx
packages/website/src/routes/ReefRoutes/Reef/Stats/index.tsx
packages/website/src/routes/ReefRoutes/Reef/Temperature/index.tsx
packages/website/src/routes/ReefRoutes/Reef/__snapshots__/index.test.tsx.snap
packages/website/src/routes/ReefRoutes/Reef/index.tsx
packages/website/src/store/Reefs/reefsListSlice.ts

- Add number formatting
- Fix typo
- Add surfaceTemperatureData

Reef detail page tweaks

---

packages/website/src/helpers/createChartData.ts
packages/website/src/routes/Homepage/ReefTable/SelectedReefCard/cardChart.tsx
packages/website/src/routes/ReefRoutes/Reef/Charts/index.tsx

Update charts style

---

packages/api/package.json
packages/api/src/app.module.ts
packages/api/src/google-cloud/google-cloud.module.ts
packages/api/src/google-cloud/google-cloud.service.ts
packages/api/src/surveys/dto/edit-survey-media.dto.ts
packages/api/src/surveys/survey-media.entity.ts
packages/api/src/surveys/surveys.controller.ts
packages/api/src/surveys/surveys.entity.ts
packages/api/src/surveys/surveys.module.ts
packages/api/src/surveys/surveys.service.ts
packages/api/src/uploads/file.decorator.ts
packages/website/src/routes/Homepage/ReefTable/__snapshots__/index.test.tsx.snap
yarn.lock

- Add get survey media endpoint
- Hide images based on hidden flag
- Return featured image when retrieving the survey list
- Add @google-cloud/storage npm package
- Add GoogleCloudService to add google cloud specific functionality (deleteFile)

Add survey-media endpoints

---

packages/website/src/routes/Homepage/SignInDialog/index.tsx
packages/website/src/services/userServices.ts
packages/website/src/store/User/types.ts
packages/website/src/store/User/userSlice.ts

Implement reset password functionality using the default firebase email

Implement reset password functionality

---

packages/website/src/routes/Homepage/RegisterDialog/index.tsx
packages/website/src/routes/Homepage/SignInDialog/index.tsx
packages/website/src/routes/Homepage/__snapshots__/index.test.tsx.snap
packages/website/src/routes/ReefRoutes/Reef/__snapshots__/index.test.tsx.snap

Improve register modal on mobile

---

packages/website/src/routes/Homepage/Map/index.tsx

Improve mobile popup

---

packages/website/src/common/NavBar/__snapshots__/index.test.tsx.snap
packages/website/src/common/NavBar/index.tsx
packages/website/src/common/Search/__snapshots__/index.test.tsx.snap
packages/website/src/common/Search/index.tsx
packages/website/src/routes/Homepage/__snapshots__/index.test.tsx.snap
packages/website/src/routes/Homepage/index.tsx
packages/website/src/routes/ReefRoutes/Reef/__snapshots__/index.test.tsx.snap

🎨 Enhance Navbar on different screens

---

packages/api/src/exception-filters/UnauthorizedFilter.ts
packages/api/src/main.ts

Messages from the back-end errors:
Bad Request: Descriptive validation error
Not Found: <Entity> with id <id> was not found
Unauthorized: You are not allowed to execute this operation
Internal Error: An unexpected error has occurred. Please try again later. (handled by the front-end)

Refactor and document api error messages

---

packages/api/migration/1599137883325-FixSurveyMediaNullConstraint.ts
packages/api/src/surveys/dto/create-survey-media.dto.ts
packages/api/src/surveys/dto/create-survey.dto.ts
packages/api/src/surveys/dto/edit-survey-media.dto.ts
packages/api/src/surveys/dto/edit-survey.dto.ts
packages/api/src/surveys/survey-media.entity.ts
packages/api/src/surveys/surveys.service.ts

- Delete null constraint from comments in survey media
- Trim comments field to avoid empty or empty-like strings
- Refactor dto objects to have correct types

Fix inconsistencies in survey controller

---

packages/api/migration/1599571050496-UpdateReefForeignKeys.ts

A migration seemed to be missing regarding the reef entity.

Add missing migration

---

packages/website/src/routes/ReefRoutes/Reef/Surveys/DeleteButton.tsx
packages/website/src/routes/Surveys/New/Form.tsx
packages/website/src/routes/Surveys/New/UploadMedia.tsx
packages/website/src/routes/Surveys/View/index.tsx
packages/website/src/services/surveyServices.ts
packages/website/src/services/uploadServices.ts
packages/website/src/store/Survey/surveySlice.ts

Add /reefs/${reefId} prefix to all implemented survey endpoints

Add reef prefix to survey endpoints

---

packages/api/src/auth/firebase-auth.guard.ts
packages/api/src/users/users.service.ts

Small fixes to the new code from PR #128.

Clean up user reef admin migration

---

packages/website/src/store/User/userSlice.ts

This PR fixes the 401 error on registration by making the `getSelf` thunk only run if no other `useSlice` action is pending.
Fixes #164.

Fix 401 error on Registration

---

packages/website/src/routes/ReefRoutes/Reef/Satellite/__snapshots__/index.test.tsx.snap
packages/website/src/routes/ReefRoutes/Reef/Satellite/index.tsx
packages/website/src/routes/ReefRoutes/Reef/Sensor/__snapshots__/index.test.tsx.snap
packages/website/src/routes/ReefRoutes/Reef/Sensor/index.tsx
packages/website/src/routes/ReefRoutes/Reef/Surveys/__snapshots__/index.test.tsx.snap
packages/website/src/routes/ReefRoutes/Reef/Surveys/index.tsx
packages/website/src/routes/ReefRoutes/Reef/Waves/__snapshots__/index.test.tsx.snap
packages/website/src/routes/ReefRoutes/Reef/__snapshots__/index.test.tsx.snap
packages/website/src/routes/ReefRoutes/Reef/index.tsx
packages/website/src/routes/ReefRoutes/Reef/styles.ts

- fix sensor card positions
- make survey and timeline larger

Fix reef details issues

---

packages/website/src/routes/Homepage/Map/sofarLayers.tsx
packages/website/src/routes/Homepage/ReefTable/__snapshots__/index.test.tsx.snap
packages/website/src/routes/Homepage/ReefTable/tableHead.tsx

Use radio buttons for tile layers

---

packages/website/src/routes/ReefRoutes/Reef/Charts/utils.ts
packages/website/src/routes/Surveys/New/Form.tsx

Add cancel button to new survey

---

packages/website/src/routes/Homepage/Map/Markers/index.tsx
packages/website/src/routes/Homepage/Map/sofarLayers.tsx
packages/website/src/routes/Homepage/ReefTable/SelectedReefCard/cardChart.tsx
packages/website/src/routes/Homepage/ReefTable/__snapshots__/index.test.tsx.snap
packages/website/src/routes/Homepage/ReefTable/index.tsx
packages/website/src/routes/ReefRoutes/Reef/Charts/index.tsx
packages/website/src/routes/ReefRoutes/Reef/Charts/utils.ts
packages/website/src/routes/ReefRoutes/Reef/Satellite/__snapshots__/index.test.tsx.snap
packages/website/src/routes/ReefRoutes/Reef/Satellite/index.tsx
packages/website/src/routes/ReefRoutes/Reef/__snapshots__/index.test.tsx.snap
packages/website/src/routes/Surveys/New/index.tsx
packages/website/src/routes/Surveys/View/Charts/index.tsx
packages/website/src/routes/Surveys/View/SurveyMediaDetails.tsx
packages/website/src/routes/Surveys/View/index.tsx

- Historical Max  value not bleaching threshold
- 7 years -> 20 years
- Order table by DHW
- Keep maxZoom when clicking
- Rename to Historical Max
- Remove survey history when creating a new survey
- No 12m on survey page
- Hide “All photos from survey point”
- Steeper charts

Misc small changes - Sept 16th

---

packages/api/src/reefs/reefs.controller.ts
packages/api/src/reefs/reefs.service.ts
packages/api/src/utils/constants.ts
packages/api/src/utils/liveData.ts
packages/api/src/utils/sofar.test.ts
packages/api/src/utils/sofar.ts
packages/api/src/utils/sofar.types.ts
packages/api/src/workers/dailyData.ts

- Add GET /reefs/<reef_id>/live_data: Fetch live data for reef with id <reef_id>
- Add liveData.ts in utils to handle the fetching of the latest data from sofar
- Refactor dailyData.ts to remove constant string (modelId and variableIDs)
- Refactor sofar.ts so that all data fetching functions return SofarValues so that we have a uniform approach
- expose util funcions (extractSofarValues, getLatestDailyData) as they are needed in liveData.ts and dailyData.ts
- Add sofar.types.ts where public types regarding sofar are stored

Add live data API endpoint

---

packages/website/src/layout/App/theme.ts
packages/website/src/routes/Homepage/Map/Popup/__snapshots__/index.test.tsx.snap
packages/website/src/routes/Homepage/Map/Popup/index.tsx
packages/website/src/routes/Homepage/ReefTable/SelectedReefCard/__snapshots__/index.test.tsx.snap
packages/website/src/routes/Homepage/ReefTable/SelectedReefCard/index.tsx
packages/website/src/routes/ReefRoutes/Reef/Charts/Tooltip/index.tsx
packages/website/src/routes/ReefRoutes/Reef/Satellite/__snapshots__/index.test.tsx.snap
packages/website/src/routes/ReefRoutes/Reef/Satellite/index.tsx
packages/website/src/routes/ReefRoutes/Reef/Sensor/__snapshots__/index.test.tsx.snap
packages/website/src/routes/ReefRoutes/Reef/Sensor/index.tsx
packages/website/src/routes/ReefRoutes/Reef/Waves/__snapshots__/index.test.tsx.snap
packages/website/src/routes/ReefRoutes/Reef/Waves/index.tsx
packages/website/src/routes/ReefRoutes/Reef/styles.ts
packages/website/src/routes/Surveys/View/observationBox.tsx

This PR is scheduled to fix https://github.com/aqualinkorg/aqualink-app/issues/241.

Change units to lowercase

---

packages/website/src/common/Search/__snapshots__/index.test.tsx.snap
packages/website/src/common/Search/index.tsx
packages/website/src/routes/Homepage/ReefTable/__snapshots__/index.test.tsx.snap
packages/website/src/routes/Homepage/ReefTable/tableHead.tsx
packages/website/src/routes/ReefRoutes/Reef/Sensor/__snapshots__/index.test.tsx.snap
packages/website/src/routes/ReefRoutes/Reef/Sensor/index.tsx
packages/website/src/routes/Surveys/View/observationBox.tsx

This PR is scheduled to fix https://github.com/aqualinkorg/aqualink-app/issues/243 and https://github.com/aqualinkorg/aqualink-app/issues/237.

Change titles and change surface sensor to 1m

---

packages/website/src/common/Footer/__snapshots__/index.test.tsx.snap
packages/website/src/common/Footer/index.tsx
packages/website/src/common/NavBar/__snapshots__/index.test.tsx.snap
packages/website/src/common/NavBar/index.tsx
packages/website/src/routes/Apply/__snapshots__/index.test.tsx.snap
packages/website/src/routes/ReefRoutes/Reef/CoralBleaching/__snapshots__/index.test.tsx.snap
packages/website/src/routes/ReefRoutes/Reef/CoralBleaching/index.tsx
packages/website/src/routes/ReefRoutes/Reef/__snapshots__/index.test.tsx.snap

This PR is scheduled to fix https://github.com/aqualinkorg/aqualink-app/issues/240.

Link navbar logo to homepage

---

packages/api/src/reefs/reefs.service.ts

Limit daily data to 90 days

---

packages/website/package.json

Closes #224 
A shot in the dark to try fix OOM issues in tests. 
Plan to rerun this PR's tests multiple times to test.
Ref - https://discuss.circleci.com/t/memory-problems-with-jest-and-workers/10297

Fix OOM issues in tests by limiting the number of workers

---

packages/api/src/surveys/surveys.service.ts
packages/website/src/routes/ReefRoutes/Reef/CardTitle/__snapshots__/index.test.tsx.snap
packages/website/src/routes/ReefRoutes/Reef/CardTitle/index.test.tsx
packages/website/src/routes/ReefRoutes/Reef/CardTitle/index.tsx
packages/website/src/routes/ReefRoutes/Reef/ReefDetails.tsx
packages/website/src/routes/ReefRoutes/Reef/index.tsx

This PR is scheduled to fix https://github.com/aqualinkorg/aqualink-app/issues/184. The designs implemented look like this:

Add featured image info on reef detail page

---

packages/website/src/routes/Homepage/ReefTable/SelectedReefCard/__snapshots__/index.test.tsx.snap
packages/website/src/routes/Homepage/ReefTable/SelectedReefCard/index.tsx
packages/website/src/routes/Surveys/View/index.tsx

Remove map and image in survey view

---

packages/api/src/google-cloud/google-cloud.controller.ts
packages/api/src/google-cloud/google-cloud.module.ts
packages/api/src/google-cloud/google-cloud.service.ts
packages/api/src/surveys/surveys.service.ts
packages/api/src/utils/google-cloud.utils.ts

GET /google-cloud/ : Fetch dangling files
DELETE /google-cloud/ : Delete dangling files

Add google cloud endpoints to handle the files in the storage

---

packages/website/src/routes/Surveys/View/index.tsx

Closes #302
(Cursor doesn't show in Window Snip, color is on hover only)

Make 'Back to Site' button fully clickable

---

packages/api/src/reefs/dto/update-reef.dto.ts
packages/api/src/reefs/reefs.controller.ts
packages/api/src/reefs/reefs.service.ts

Add reef manager authorization
Accept longitude and latitude instead of polygon

Fix update reef endpoint

---

packages/api/migration/1602489219253-AddExclusionDatesTable.ts
packages/api/src/reefs/exclusion-dates.entity.ts
packages/api/src/workers/dailyData.test.ts
packages/api/src/workers/dailyData.ts

- Add exclusion dates table
- Filter out spotter data from spotter on excluded dates

Add spotter exclusion dates

---

packages/website/src/layout/App/index.tsx
packages/website/src/routes/Homepage/ReefTable/SelectedReefCard/__snapshots__/index.test.tsx.snap
packages/website/src/routes/Homepage/RegisterDialog/__snapshots__/index.test.tsx.snap
packages/website/src/routes/Homepage/RegisterDialog/index.tsx
packages/website/src/routes/ReefRoutes/Reef/__snapshots__/index.test.tsx.snap
packages/website/src/routes/Terms/__snapshots__/index.test.tsx.snap
packages/website/src/routes/Terms/index.test.tsx
packages/website/src/routes/Terms/index.tsx

The purpose of this PR is to create an terms page. The design implemented looks like this:

Terms Page

---

packages/website/src/routes/RegisterSite/index.tsx

Remove CartoDB insert

---

packages/website/src/common/MenuDrawer/__snapshots__/index.test.tsx.snap
packages/website/src/common/MenuDrawer/index.tsx
packages/website/src/routes/ReefRoutes/Reef/__snapshots__/index.test.tsx.snap
packages/website/src/routes/Terms/__snapshots__/index.test.tsx.snap

The purpose of this PR is to open the contribution links on new tabs.

Open contribution links on new tab

---

packages/website/src/routes/ReefRoutes/Reef/Waves/index.tsx

The purpose of this PR is to fix the iOS wind card issue. The design looks like this:
- Before:
- After:

Fix Wind Card on iOS

---

packages/api/migration/1602761349506-RefactorApplicationStatus.ts
packages/api/src/reefs/dto/create-reef.dto.ts
packages/api/src/reefs/dto/update-reef.dto.ts
packages/api/src/reefs/reefs.entity.ts
packages/api/src/reefs/reefs.service.ts

Refactor application status

---

packages/website/src/helpers/surveyMedia.ts

The purpose of this PR is to sort the media carousels on survey details page by point of interest name.

Sort media by survey point name

---

packages/website/src/routes/Homepage/Map/Popup/index.test.tsx
packages/website/src/routes/ReefRoutes/Reef/Surveys/SurveyCard/index.test.tsx
packages/website/src/routes/Surveys/New/UploadMedia.tsx

The purpose of this PR is to disable the upload button if a media upload request is pending. The design implemented looks like this:

Disable Image Upload While Already Loading

---

packages/api/src/pipes/parse-date.pipe.ts
packages/api/src/reefs/reefs.controller.ts
packages/api/src/reefs/reefs.service.ts
packages/api/src/utils/sofar.ts

- Add new endpoint on reefs controller: GET /reefs/:reef_id/spotter_data
- Add parse date pipe to parse query params

API - Get spotter raw temperature data within time range

---

packages/website/src/common/Chart/ChartWithTooltip.tsx
packages/website/src/common/Chart/Tooltip/__snapshots__/index.test.tsx.snap
packages/website/src/common/Chart/Tooltip/index.tsx
packages/website/src/common/Chart/index.tsx
packages/website/src/common/Chart/utils.ts
packages/website/src/routes/Homepage/ReefTable/SelectedReefCard/__snapshots__/index.test.tsx.snap

Update tooltip with colors

---

packages/website/src/routes/Landing/__snapshots__/index.test.tsx.snap
packages/website/src/routes/Landing/index.tsx

The purpose of this PR is to fix the issue below that appears on iOS devices.

Fix landing page iOS issue

---

packages/website/src/index.tsx

I noticed the following bug: when trying to reach a reef's application page, the request to get the application was sent endlessly, because the application page component's `useEffect` had a `user` dependency, and `user` was always updating (because his token was always changing). With this approach, we only get a new token on `401` status, and the request is sent only once (after a possible token expiration failure).

Reset token only on 401 status

---

packages/website/src/common/ErrorPage/__snapshots__/index.test.tsx.snap
packages/website/src/common/Footer/__snapshots__/index.test.tsx.snap
packages/website/src/common/Footer/index.tsx
packages/website/src/routes/Landing/__snapshots__/index.test.tsx.snap
packages/website/src/routes/ReefRoutes/Reef/__snapshots__/index.test.tsx.snap
packages/website/src/routes/RegisterSite/__snapshots__/index.test.tsx.snap
packages/website/src/routes/Terms/__snapshots__/index.test.tsx.snap

Noticed some links that were not redirecting to the correct place.

Set footer link to /map

---

packages/website/src/routes/ReefRoutes/Reef/ReefInfo/__snapshots__/index.test.tsx.snap
packages/website/src/routes/ReefRoutes/Reef/ReefInfo/index.tsx
packages/website/src/routes/ReefRoutes/Reef/__snapshots__/index.test.tsx.snap

Add regionName to reef details page

---

packages/website/src/routes/HomeMap/index.tsx

The purpose of this PR is to fix a jss typo.

Fix jss typo

---

packages/website/src/routes/HomeMap/ReefTable/index.tsx
packages/website/src/store/Reefs/reefsListSlice.ts
packages/website/src/store/Reefs/types.ts

The purpose of this PR is to close https://github.com/aqualinkorg/aqualink-app/issues/408.

Fix spotter only button "back" issue

---

packages/website/src/common/Search/index.tsx
packages/website/src/helpers/reefUtils.ts
packages/website/src/routes/HomeMap/Map/index.tsx

The purpose of this PR is to close https://github.com/aqualinkorg/aqualink-app/issues/424.

Center map to reef with max dhd

---

packages/website/src/common/NavBar/index.tsx
packages/website/src/common/Search/index.test.tsx
packages/website/src/common/Search/index.tsx
packages/website/src/routes/HomeMap/ReefTable/SelectedReefCard/index.tsx
packages/website/src/routes/HomeMap/__snapshots__/index.test.tsx.snap
packages/website/src/routes/HomeMap/index.tsx
packages/website/src/routes/ReefRoutes/Reef/FeaturedMedia/index.tsx
packages/website/src/routes/ReefRoutes/Reef/ReefDetails.tsx
packages/website/src/routes/ReefRoutes/Reef/Surveys/SurveyCard/__snapshots__/index.test.tsx.snap
packages/website/src/routes/ReefRoutes/Reef/Surveys/SurveyCard/index.tsx
packages/website/src/routes/ReefRoutes/Reef/Surveys/__snapshots__/index.test.tsx.snap
packages/website/src/routes/ReefRoutes/Reef/index.tsx

The purpose of this PR is to close https://github.com/aqualinkorg/aqualink-app/issues/452.

Link featured images to surveys

---

packages/website/src/helpers/validators.ts
packages/website/src/routes/ReefRoutes/Reef/Map/index.tsx
packages/website/src/routes/ReefRoutes/Reef/ReefInfo/EditForm/index.tsx
packages/website/src/routes/ReefRoutes/Reef/ReefInfo/EditForm/useFormField.ts
packages/website/src/routes/RegisterSite/LocationMap/index.tsx
packages/website/src/routes/RegisterSite/index.tsx

The purpose of this PR is to ensure that:
- `|latitude| <= 90`
- `|longitude| <= 180`

Add location coordinates validation

---

packages/website/src/layout/App/App.css
packages/website/src/routes/HomeMap/Map/Popup/index.tsx

The purpose of this PR is to close https://github.com/aqualinkorg/aqualink-app/issues/459.
Designs;
| 3840x2160 |
|---|
| ![screencapture-localhost-3000-map-2021-02-17-18_46_25](https://user-images.githubusercontent.com/64922890/108237453-98371080-7150-11eb-8d04-b34ba15281fc.png) |

Scale map tooltip on large screens

---

packages/website/src/routes/HomeMap/ReefTable/__snapshots__/index.test.tsx.snap
packages/website/src/routes/HomeMap/ReefTable/index.tsx

Show spotter filter to all users

Remove superAdmin restriction for spotterFilter

---

packages/api/cloud-functions/index.ts
packages/api/migration/1615290662268-AddExtraConstraintOnTimeSeries.ts
packages/api/migration/1615299917998-AppendNewMetrics.ts
packages/api/migration/1615469917998-AppendNewMetrics.ts
packages/api/package.json
packages/api/scripts/backfill-spotter-data.ts
packages/api/src/time-series/metrics.entity.ts
packages/api/src/time-series/time-series.entity.ts
packages/api/src/utils/spotter-time-series.ts
packages/api/src/workers/spotterTimeSeries.ts

- New back-fill script to add spotter data in the time-series table
- New cloud function to schedule daily updates of spotter data

Timeseries spotter data

---

packages/api/.gcloudignore
packages/api/app-programize.yaml
packages/api/package.json
packages/website/.firebaserc
packages/website/README.md
packages/website/firebase.json
packages/website/package.json

Add new API and Firebase targets to help the dev team deploy QA versions

Add programize deployment targets

---

packages/api/src/reefs/reefs.controller.ts
packages/api/src/reefs/reefs.service.ts

Add query params `start` and `end` to be able to select range of data.
If params are omitted last 90 data points are returned

Daily data fix

---

packages/api/src/time-series/dto/poi-data-range.dto.ts
packages/api/src/time-series/dto/reef-data-range.dto.ts
packages/api/src/time-series/dto/reef-data.dto.ts
packages/api/src/time-series/time-series.controller.ts
packages/api/src/time-series/time-series.service.ts
packages/website/src/routes/ReefRoutes/SurveyPoint/__snapshots__/index.test.tsx.snap

Group time series data by source.
Returning object:
```js
{
metric: {
hobo: [data]
spotter: [data]
}
}
```

Return time series data by source [backend only]

---

packages/website/src/routes/Landing/__snapshots__/index.test.tsx.snap
packages/website/src/routes/Landing/index.tsx

Move title up

---

packages/api/src/utils/spotter-time-series.ts
packages/website/src/routes/ReefRoutes/SurveyPoint/__snapshots__/index.test.tsx.snap

Reduce concurrency of the backfill spotter data script

Spotter data backfill fix

---

packages/api/Dockerfile
packages/api/scripts/sst-backfill.ts
packages/website/src/common/Chart/ChartWithCard/Chart.tsx
packages/website/src/common/Chart/ChartWithCard/DownloadCSVButton.tsx
packages/website/src/custom.d.ts
packages/website/src/helpers/map.ts
packages/website/src/helpers/surveys.ts
packages/website/src/routes/Surveys/View/index.tsx

Co-authored-by: Eric Boucher <eric.p.boucher@gmail.com>

Frontend tweaks to develop-hobo release

---

packages/api/src/utils/spotter-time-series.ts

Start spotter backfill from the current day

Spotter backfill up to now instead of yesterday

---

packages/api/src/utils/sofar.test.ts
packages/api/src/workers/dailyData.test.ts
packages/website/package.json
packages/website/src/common/Chart/ChartWithCard/helpers.ts
packages/website/src/common/Chart/ChartWithCard/index.tsx

The purpose of this PR is to clean up the `ChartWithCard` component, by removing some unnecessary data filtering and relying on the API to fetch correct data inside the desired range.

Remove unnecessary data filtering

---

.circleci/config.yml
packages/api/src/seeds/create-reefs.seeds.ts

Missing SURFACE_TEMPERATURE -> TOP_TEMPERATURE in create reef DTO causing failed builds for cloud functions
Adding cloud function build step to CI

Final SURFACE_TEMPERATURE -> TOP_TEMPERATURE change

---

.circleci/config.yml

Added an extra CI step at the end to run all migrations
Changed image of database to match the one we use
https://github.com/aqualinkorg/aqualink-app/issues/463

CI - Add migrations test

---

packages/website/src/common/SiteDetails/index.tsx
packages/website/src/helpers/bleachingAlertIntervals.ts
packages/website/src/helpers/map.ts
packages/website/src/routes/HomeMap/Map/Markers/ReefMarker.tsx
packages/website/src/routes/HomeMap/Map/Markers/index.tsx
packages/website/src/routes/HomeMap/Map/Popup/index.tsx
packages/website/src/store/Reefs/reefsListSlice.ts

A `makeStyles` hook wasn't defined properly, meaning we ended up conditionally calling it.
Test:  http://aqua-bug.surge.sh

Fix "deployed buoys only " switch not working

---

packages/api/cloud-functions/index.ts

The ping URL was not correct. An extra `/` was present causing the request to fail with 404 error code.

Fix ping url

---

packages/website/src/common/Chart/ChartWithCard/Chart.tsx
packages/website/src/common/Chart/ChartWithCard/TempAnalysis.tsx
packages/website/src/common/Chart/ChartWithCard/index.tsx

- Keep them side by side until small screens
- Add padding below date-range
Deployed on staging
- https://aqualink-app-staging.web.app/reefs/1630 (spotter)
- https://aqualink-app-staging.web.app/reefs/1632 (hobo)

Improve scaling for the charts and stats box

---

packages/website/src/routes/Surveys/View/SurveyMediaDetails.tsx
packages/website/src/routes/Surveys/View/index.tsx
packages/website/src/store/Survey/surveySlice.ts

The purpose of this PR is to close https://github.com/aqualinkorg/aqualink-app/issues/545.

Fix unnecessary reload on featured image update

---

packages/website/src/common/Chart/ChartWithCard/helpers.ts
packages/website/src/common/Chart/ChartWithCard/index.tsx
packages/website/src/helpers/dates.ts

The purpose of this PR is to fix the reef detailed chart not fetching all data on first load bug

Fix detailed chart not fetching all data on first load bug

---

packages/api/src/sensors/sensors.service.ts
packages/api/src/utils/time-series.utils.ts

When coral-atlas-api merged with the master, the time-series refactor changes were not applied on `time-series-utils` which caused the time-series endpoints to fail

Important: Apply refactor changes on time-series utils

---

packages/api/src/utils/constants.ts
packages/api/src/utils/sofar.ts

Address #568 
Changes:
- smartMooringData are fetched from sensor-data endpoint
- sensorPositions shifted to a 1-based indexing (1 is closest to sensor)

Change sofar api for spotter

---

packages/website/src/helpers/requests.ts
packages/website/src/index.tsx
packages/website/src/services/uploadServices.ts

The purpose of this PR is to add an upload media hotfix.

Fix API url issue in upload media services

---

packages/api/src/workers/check-video-streams.ts

Add condition to check if slack responded with a successful request.
Log errors and warnings returned by slack, in case of an unsuccessful request.
Log message in stdout regardless to always have the info available.

Increase logging on check video streams script

---

packages/website/src/routes/Dashboard/index.tsx
packages/website/src/routes/Tracker/index.tsx

The purpose of this PR is to fix the Minderoo collection not being properly fetched bug on production.

Fix minderoo collection fetching bug

---

packages/api/migration/1627912428897-UpdateSourceConstraint.ts
packages/api/src/reefs/sources.entity.ts

Related issue https://github.com/aqualinkorg/aqualink-app/issues/608

Add sensor id on partial constraint

---

.circleci/config.yml
packages/api/.gitignore
packages/api/test/jest.json

Break circleci CI/CD job into 4 flows:
- build_dependencies:
Install dependencies, and saves them on a cache to be used on the other scripts
- test api:
Initializes the db, runs the tests and the linter for the api package
Added cache for the jest test to speed up their execution
- test web:
Runs the tests and linter for the website package
- Build app:
Build app and cloud-functions

Optimize circleci

---

packages/api/ONBOARDING.md
packages/api/scripts/augment-reef-data.ts
packages/api/scripts/backfill-sofar-time-series.ts
packages/api/scripts/upload-hobo-data.ts
packages/api/src/utils/spotter-time-series.ts
packages/api/src/utils/sst-time-series.ts
packages/api/src/utils/time-series.utils.ts
packages/api/src/workers/dailyData.ts

Add comments on all major script to increase verbosity and clarify selected solutions

Add onboarding doc and improve inline comments

---

packages/api/src/utils/constants.ts
packages/api/src/utils/liveData.ts
packages/api/src/utils/sofar.test.ts
packages/api/src/workers/dailyData.test.ts
packages/api/src/workers/dailyData.ts

Noaa has deprecated their OperationalWaveModel

Transition to SofarOperationalWaveModel instead of Noaa model

---

packages/api/migration/1636644741257-addLostSpotterStatusAndInvasiveSpecies.ts
packages/api/src/sites/sites.entity.ts
packages/api/src/surveys/survey-media.entity.ts
packages/website/src/common/SiteDetails/Surveys/__snapshots__/index.test.tsx.snap
packages/website/src/common/SiteDetails/Waves/__snapshots__/index.test.tsx.snap
packages/website/src/constants/uploadDropdowns.ts
packages/website/src/helpers/numberUtils.ts
packages/website/src/routes/SiteRoutes/Site/__snapshots__/index.test.tsx.snap
packages/website/src/store/Survey/types.ts

- Fix negative wind issue
- Add "lost" status for spotters
- Add invasive-species category (Fixes #625)

Fix negative wind and add lost spotter status

---

packages/api/src/surveys/surveys.controller.ts
packages/api/src/uploads/file.decorator.ts

Allow development without file upload configuration

Allow development without file upload configuration (GCS Bucket)

---

packages/api/src/pipes/parse-date.pipe.ts
packages/api/src/sensors/sensors.controller.ts
packages/api/src/sensors/sensors.service.ts
packages/api/src/sites/sites.controller.ts
packages/api/src/sites/sites.service.ts
packages/api/src/time-series/time-series.controller.ts
packages/api/src/time-series/time-series.service.ts
packages/api/src/utils/dates.ts
packages/api/src/utils/time-series.utils.ts
packages/website/src/common/Chart/MultipleSensorsCharts/Header.tsx
packages/website/src/common/Chart/MultipleSensorsCharts/helpers.ts
packages/website/src/common/Chart/MultipleSensorsCharts/index.tsx
packages/website/src/common/Chart/MultipleSensorsCharts/types.ts
packages/website/src/helpers/requests.ts
packages/website/src/helpers/siteUtils.ts
packages/website/src/hooks/useQueryParams.ts
packages/website/src/mocks/mockHoboDataRange.ts
packages/website/src/services/siteServices.ts
packages/website/src/store/Sites/helpers.ts
packages/website/src/store/Sites/types.ts

The purpose of this PR is to close
TODOs:

Robust parameter generation & URL date selector for Sites

---

packages/api/migration/1643364520677-DataUploadsAddCreatedUpdatedColumns.ts
packages/api/src/data-uploads/data-uploads.entity.ts
packages/api/src/data-uploads/data-uploads.service.ts
packages/api/src/utils/uploads/upload-sonde-data.ts
packages/website/src/common/Chart/CombinedCharts.tsx
packages/website/src/common/Chart/MultipleSensorsCharts/AnalysisCard.tsx
packages/website/src/common/Chart/MultipleSensorsCharts/helpers.ts
packages/website/src/common/NewSurveyPointDialog/__snapshots__/index.test.tsx.snap
packages/website/src/common/NewSurveyPointDialog/index.test.tsx
packages/website/src/common/NewSurveyPointDialog/index.tsx
packages/website/src/common/SiteDetails/WaterSampling/__snapshots__/index.test.tsx.snap
packages/website/src/common/SiteDetails/WaterSampling/index.tsx
packages/website/src/common/SiteDetails/WaterSampling/utils.ts
packages/website/src/common/SiteDetails/index.tsx
packages/website/src/helpers/map.ts
packages/website/src/helpers/siteUtils.ts
packages/website/src/routes/SiteRoutes/Site/index.tsx
packages/website/src/routes/SiteRoutes/UploadData/DropZone.tsx
packages/website/src/routes/SiteRoutes/UploadData/NewPointDialog.tsx
packages/website/src/routes/SiteRoutes/UploadData/Selectors.tsx
packages/website/src/routes/SiteRoutes/UploadData/index.tsx
packages/website/src/routes/Surveys/New/MediaCard.tsx
packages/website/src/routes/Surveys/New/UploadMedia.tsx
packages/website/src/store/Sites/types.ts

The purpose of this PR is to introduce the following enhancements:

Sonde Upload Enhancements

---

package.json
packages/api/src/google-cloud/google-cloud.service.ts
packages/api/src/workers/dailyData.ts
packages/website/src/common/NewSurveyPointDialog/index.tsx
packages/website/src/helpers/errors.ts
packages/website/src/routes/SiteRoutes/UploadData/index.tsx
packages/website/src/store/Collection/collectionSlice.ts
packages/website/src/store/Sites/selectedSiteSlice.ts
packages/website/src/store/Sites/sitesListSlice.ts
packages/website/src/store/Survey/surveyListSlice.ts
packages/website/src/store/Survey/surveySlice.ts
packages/website/src/store/User/userSlice.ts
yarn.lock

The purpose of this PR is to upgrade `typescript@4.5.5`.

Upgrade typescript

---

packages/api/src/workers/dailyData.test.ts
packages/website/src/common/Dialog/index.tsx
packages/website/src/common/SiteDetails/Surveys/__snapshots__/index.test.tsx.snap
packages/website/src/common/SiteDetails/Surveys/index.tsx
packages/website/src/layout/App/index.tsx
packages/website/src/routes/SiteRoutes/Site/__snapshots__/index.test.tsx.snap
packages/website/src/services/siteServices.ts
packages/website/src/store/Survey/surveySlice.ts

The purpose of this PR is to close https://github.com/aqualinkorg/aqualink-app/issues/653.
This PR spots all the unhandled promises in our code base and adds an error callback to all of them.

Fix unhandled promise rejections

---

packages/api/scripts/backfill-daily-data.ts
packages/api/scripts/backfill-sofar-time-series.ts
packages/api/src/sensors/sensors.service.ts
packages/api/src/sites/sites.service.ts
packages/website/src/routes/SiteRoutes/Site/SiteInfo/ExclusionDatesDialog/ConfirmationDialog.tsx
packages/website/src/routes/SiteRoutes/Site/SiteInfo/ExclusionDatesDialog/index.tsx

Add a few log statements to debug surprising behaviors
- null spotters during updates
- time-series delete statements not working

Improve exclusion date data delete and add logging

---

packages/api/migration/1649940478607-addGCloudLocationForDataUploads.ts
packages/api/src/data-uploads/data-uploads.entity.ts
packages/api/src/google-cloud/google-cloud.service.ts
packages/api/src/utils/uploads/upload-sheet-data.ts
packages/website/src/routes/SiteRoutes/UploadData/index.tsx

The purpose of this PR is to close https://github.com/aqualinkorg/aqualink-app/issues/701

Save data uploads to gcloud

---

packages/website/src/common/Chart/MultipleSensorsCharts/Header.tsx
packages/website/src/common/Chart/MultipleSensorsCharts/index.tsx
packages/website/src/common/Chart/MultipleSensorsCharts/types.ts
packages/website/src/common/SiteDetails/Sensor/index.tsx
packages/website/src/routes/SiteRoutes/Site/__snapshots__/index.test.tsx.snap
packages/website/src/routes/SiteRoutes/Site/index.tsx

Default to showing one month of time series data instead of 3.

Default to 1 month of time series data. Hide spotter application

---

packages/website/src/store/Sites/helpers.ts

This fixes an issue where our LatestData was not actually getting filtered to keep the latest data for each metric.
cc @echaidemenos

Fix an issue with LatestData filtering

---

packages/website/src/common/Chart/MultipleSensorsCharts/ChartWithCard.tsx
packages/website/src/common/Chart/MultipleSensorsCharts/DownloadCSVButton.tsx
packages/website/src/common/Chart/MultipleSensorsCharts/DownloadCSVDialog.tsx
packages/website/src/common/Chart/MultipleSensorsCharts/helpers.ts
packages/website/src/common/Chart/MultipleSensorsCharts/index.tsx
packages/website/src/common/Chart/index.tsx

The purpose of this PR is to close https://github.com/aqualinkorg/aqualink-app/issues/704
Changes the position of `Download CSV` button in site view. Adds a dialog with checkboxes from all non zero values for the user to download. It downloads only data between the selected dates on the charts.
Example output
```
﻿timestamp,satelliteTemperature_noaa,windSpeed_spotter,significantWaveHeight_spotter,topTemperature_spotter,bottomTemperature_spotter,sstAnomaly_noaa
2022-04-18T21:00:00.000Z,16.11,,,,,
2022-04-27T21:00:00.000Z,,14.4,0.82,,,
2022-04-27T22:00:00.000Z,,12.96,0.78,20.906666666666666,20.86,
2022-04-27T23:00:00.000Z,,12.96,0.84,20.860000000000003,20.86,
2022-04-28T00:00:00.000Z,,14.4,0.68,20.80666666666667,20.880000000000003, …
```

Include all data from charts to csv file

---

packages/api/src/main.ts

Let developers run the API locally without requiring Firebase settings

Run without firebase env

---

packages/website/src/routes/Landing/Card/index.tsx
packages/website/src/routes/Landing/__snapshots__/index.test.tsx.snap
packages/website/src/routes/Landing/index.tsx

This change fix scroll down button '/' page on mobile device
With old version scrolling not full height
https://user-images.githubusercontent.com/90055175/170992170-74c3c8c9-fe50-4029-9c8c-24fd87c5519b.mp4

Replace scrollTo with scrollIntoView

---

packages/website/src/common/Search/index.tsx

Add check to search site id, and if we on already on this site, do nothing
Fixes issue #743

Not change page, if already on it

---

packages/api/src/utils/sofar.test.ts
packages/api/src/workers/dailyData.test.ts
packages/website/src/common/SiteDetails/CardWithTitle/index.tsx
packages/website/src/common/SiteDetails/index.tsx

Delete switch button and move 3D model to survey image instead it if available 
Before: 
After:

Use 3D model as the featured image

---

packages/website/package.json
packages/website/src/common/Chart/MultipleSensorsCharts/DownloadCSVButton.tsx
packages/website/src/common/Chart/MultipleSensorsCharts/DownloadCSVDialog.tsx
packages/website/src/common/Chart/MultipleSensorsCharts/index.tsx
packages/website/src/common/Chart/MultipleSensorsCharts/types.ts
packages/website/src/index.tsx
yarn.lock

This PR resolve https://github.com/aqualinkorg/aqualink-app/issues/806
This PR adds 3 check boxes with the following options:
- Additional Data: Downloads all available metrics from all available sources for the current time window.
- All Dates: Ignores the dates from the time picker and downloads data from all available dates
- Hourly Data: Checked by default. If unchecked, data will not be averaged per hour

CSV data downloads improvements

---

packages/website/package.json
packages/website/src/common/ErrorPage/__snapshots__/index.test.tsx.snap
packages/website/src/common/RegisterDialog/index.tsx
packages/website/src/common/SignInDialog/__snapshots__/index.test.tsx.snap
packages/website/src/common/SignInDialog/index.tsx
packages/website/src/common/SurveyForm/index.tsx
packages/website/src/routes/Landing/__snapshots__/index.test.tsx.snap
packages/website/src/routes/RegisterSite/__snapshots__/index.test.tsx.snap
packages/website/src/routes/SiteRoutes/Site/__snapshots__/index.test.tsx.snap
packages/website/src/routes/SiteRoutes/SiteApplication/Form/__snapshots__/index.test.tsx.snap
packages/website/src/routes/SiteRoutes/SiteApplication/Form/index.tsx
packages/website/src/routes/SiteRoutes/SurveyPoint/__snapshots__/index.test.tsx.snap
packages/website/src/routes/Terms/__snapshots__/index.test.tsx.snap
yarn.lock

This PR resolves https://github.com/aqualinkorg/aqualink-app/issues/816
In order to resolve the problem, it also updates `react-hook-form` to v7.
To solve the issue, we implemented a handler for the validation failure and we sent the reset email if the email field is valid

Fix password reset would require password

---

packages/api/scripts/upload-hui-data.ts
packages/api/src/surveys/dto/create-survey-media.dto.ts
packages/api/src/surveys/surveys.service.ts
packages/website/.env.example
packages/website/src/common/SiteDetails/Surveys/SurveyCard/index.test.tsx
packages/website/src/common/SiteDetails/Surveys/Timeline/index.test.tsx
packages/website/src/common/SiteDetails/Surveys/index.test.tsx
packages/website/src/common/SurveyForm/index.tsx
packages/website/src/common/SurveyPointSelector/index.tsx
packages/website/src/mocks/mockSurveyList.ts
packages/website/src/routes/SiteRoutes/Site/index.test.tsx
packages/website/src/routes/SiteRoutes/SiteApplication/Form/index.tsx
packages/website/src/routes/SiteRoutes/SurveyPoint/index.test.tsx
packages/website/src/routes/Surveys/New/MediaCard.tsx
packages/website/src/routes/Surveys/New/UploadMedia.tsx
packages/website/src/routes/Surveys/View/MediaDetails/MediaPointName.tsx
packages/website/src/routes/Surveys/View/MediaDetails/SliderCard.tsx
packages/website/src/routes/Surveys/View/MediaDetails/__snapshots__/index.test.tsx.snap
packages/website/src/routes/Surveys/View/MediaDetails/index.test.tsx
packages/website/src/routes/Surveys/View/MediaDetails/index.tsx
packages/website/src/routes/Surveys/View/index.tsx
packages/website/src/services/userServices.ts
packages/website/src/setupTests.ts
packages/website/src/store/Survey/surveySlice.ts
packages/website/src/store/Survey/types.ts
packages/website/src/utils/types.ts

This PR add edit capability to the previous implemented survey edit. The user can select either a existing point or create a new one.

Add edit survey point in survey details media card

---

packages/website/src/common/ErrorPage/__snapshots__/index.test.tsx.snap
packages/website/src/common/MenuDrawer/__snapshots__/index.test.tsx.snap
packages/website/src/common/MenuDrawer/index.tsx
packages/website/src/routes/Landing/__snapshots__/index.test.tsx.snap
packages/website/src/routes/SiteRoutes/Site/__snapshots__/index.test.tsx.snap
packages/website/src/routes/SiteRoutes/SurveyPoint/__snapshots__/index.test.tsx.snap
packages/website/src/routes/Terms/__snapshots__/index.test.tsx.snap

Update navbar links "Stories" to "Highlighted Sites"

Update "Stories" to "Highlighted Sites"

---

packages/api/ormconfig.ts
packages/api/src/sites/sites.service.ts
packages/api/src/utils/constants.ts

Load the env in one place and make sure tests don't send Slack notifications

Load env files in one place

---

packages/website/src/routes/Faq/__snapshots__/index.test.tsx.snap
packages/website/src/routes/Faq/index.tsx

I updated the code I previously sent to you Eric that was named index.html. I also removed the div for "How do I upload Surveys" Since I wrote a new text for this one.

Improve FAQ on how to upload data

---

packages/website/src/routes/Faq/__snapshots__/index.test.tsx.snap
packages/website/src/routes/Faq/index.tsx

Removed and added spaces on the FAQ page.

Edit spaces on the FAQ page

---

packages/api/src/utils/uploads/upload-sheet-data.ts
packages/website/src/routes/Faq/__snapshots__/index.test.tsx.snap
packages/website/src/routes/Faq/index.tsx

Fixes a bug where data uploads would fail

Fix save batch would not update values

---

packages/website/src/routes/SiteRoutes/Site/SiteInfo/EditForm/index.tsx

resolves https://github.com/aqualinkorg/aqualink-app/issues/875

Fix could not update site info when site has a spotter

---

packages/website/src/common/ErrorPage/__snapshots__/index.test.tsx.snap
packages/website/src/common/NavBar/__snapshots__/index.test.tsx.snap
packages/website/src/common/NavBar/index.tsx
packages/website/src/helpers/requests.ts
packages/website/src/routes/Landing/__snapshots__/index.test.tsx.snap
packages/website/src/routes/SiteRoutes/Site/__snapshots__/index.test.tsx.snap
packages/website/src/routes/SiteRoutes/SurveyPoint/__snapshots__/index.test.tsx.snap
packages/website/src/routes/Terms/__snapshots__/index.test.tsx.snap

resolves https://github.com/aqualinkorg/aqualink-app/issues/882
Basically adds an axios response interceptor in `NavBar`, checking for statuses `401` or `403`, logouts the user the then show the login dialog.

Show login dialog on unauthorized request result

---

.github/workflows/build_website.yml
packages/website/src/common/Chart/MultipleSensorsCharts/Chart.tsx
packages/website/src/common/Chart/MultipleSensorsCharts/ChartWithCard.tsx
packages/website/src/common/Chart/MultipleSensorsCharts/__snapshots__/index.test.tsx.snap
packages/website/src/common/Chart/MultipleSensorsCharts/index.tsx
packages/website/src/common/SiteDetails/WaterSampling/index.tsx
packages/website/src/common/SiteDetails/WaterSampling/utils.ts
packages/website/src/constants/chartConfigs/huiConfig.ts
packages/website/src/constants/chartConfigs/metlogConfig.ts
packages/website/src/constants/chartConfigs/sondeConfig.ts
packages/website/src/constants/chartConfigs/spotterConfig.ts
packages/website/src/mocks/mockDataRange.ts
packages/website/src/mocks/mockTimeSeries.ts
packages/website/src/utils/types.ts

This PR aims to simplify `MultipleSensorsCharts`. Also resolves a small bug where surface temperature would show even if there was no data.

Refactor MultipleSensorsCharts

---

packages/website/src/common/Chart/MultipleSensorsCharts/DownloadCSVButton.tsx
packages/website/src/common/Chart/MultipleSensorsCharts/__snapshots__/index.test.tsx.snap
packages/website/src/common/Chart/MultipleSensorsCharts/index.tsx

resolves https://github.com/aqualinkorg/aqualink-app/issues/914
Updates the condition of placing extra padding

Fix Download CSV button position

---

packages/website/src/common/ErrorPage/__snapshots__/index.test.tsx.snap
packages/website/src/common/NavBar/__snapshots__/index.test.tsx.snap
packages/website/src/common/NavBar/index.tsx
packages/website/src/common/RouteButtons/__snapshots__/index.test.tsx.snap
packages/website/src/common/RouteButtons/index.tsx
packages/website/src/routes/Landing/__snapshots__/index.test.tsx.snap
packages/website/src/routes/SiteRoutes/Site/__snapshots__/index.test.tsx.snap
packages/website/src/routes/SiteRoutes/SurveyPoint/__snapshots__/index.test.tsx.snap
packages/website/src/routes/Terms/__snapshots__/index.test.tsx.snap

- Update nav links
- Add spacing for sign in buttons on mobile

Update nav links

---

packages/website/src/common/SiteDetails/CoralBleaching/__snapshots__/index.test.tsx.snap
packages/website/src/common/SiteDetails/CoralBleaching/index.test.tsx
packages/website/src/common/SiteDetails/CoralBleaching/index.tsx
packages/website/src/common/SiteDetails/Satellite/__snapshots__/index.test.tsx.snap
packages/website/src/common/SiteDetails/WaterSampling/__snapshots__/index.test.tsx.snap
packages/website/src/common/SiteDetails/Waves/__snapshots__/index.test.tsx.snap
packages/website/src/common/SiteDetails/index.tsx
packages/website/src/common/UpdateInfo/__snapshots__/index.test.tsx.snap
packages/website/src/common/UpdateInfo/index.tsx
packages/website/src/mocks/mockDailyData.ts
packages/website/src/routes/SiteRoutes/Site/__snapshots__/index.test.tsx.snap
packages/website/src/routes/SiteRoutes/Site/index.tsx
packages/website/src/routes/Surveys/View/SurveyDetails.tsx

Use latest data for coral bleaching alert level

---

packages/website/src/common/ErrorPage/__snapshots__/index.test.tsx.snap
packages/website/src/common/MenuDrawer/__snapshots__/index.test.tsx.snap
packages/website/src/common/MenuDrawer/index.tsx
packages/website/src/common/RouteButtons/__snapshots__/index.test.tsx.snap
packages/website/src/common/RouteButtons/index.tsx
packages/website/src/routes/Landing/__snapshots__/index.test.tsx.snap
packages/website/src/routes/SiteRoutes/Site/__snapshots__/index.test.tsx.snap
packages/website/src/routes/SiteRoutes/SurveyPoint/__snapshots__/index.test.tsx.snap
packages/website/src/routes/Terms/__snapshots__/index.test.tsx.snap
packages/website/src/routes/Uploads/__snapshots__/index.test.tsx.snap
packages/website/src/routes/monitoring/__snapshots__/index.test.tsx.snap

Add Bristlemouth Explorer

---

packages/website/src/common/Chart/ChartWithTooltip.tsx

Fixes https://github.com/aqualinkorg/aqualink-app/issues/994

Fix tooltip position

---

packages/api/src/data-uploads/data-uploads.controller.ts
packages/website/src/common/SiteDetails/SketchFab/index.tsx
packages/website/src/routes/SiteRoutes/UploadData/HistoryTable.tsx
packages/website/src/routes/SiteRoutes/UploadData/index.tsx
packages/website/src/services/uploadServices.ts

This PR fixes an issue, where site manager were not able to delete their sites' uploads.

Fix auth for deleting upload

---

packages/website/src/common/Chart/ChartWithTooltip.tsx
packages/website/src/common/SiteDetails/index.tsx
yarn.lock

Update HUI to show alert card instead of spotter card

---

packages/website/src/routes/About/__snapshots__/index.test.tsx.snap
packages/website/src/routes/About/index.tsx
packages/website/src/routes/Faq/__snapshots__/index.test.tsx.snap
packages/website/src/routes/Faq/index.tsx

I added tutorial on how to add your personal Sofar Spotter to Aqualink, and added the "How to use Aqualink vide to the About and FAQ page.

Add video and text to the FAQ and About page

---

packages/website/src/common/Chip/index.tsx
packages/website/src/common/Search/index.tsx
packages/website/src/common/SiteDetails/WaterSampling/utils.ts
packages/website/src/hooks/useQueryParams.ts
packages/website/src/layout/App/index.test.tsx
packages/website/src/layout/App/index.tsx
packages/website/src/routes/Dashboard/Content.tsx
packages/website/src/routes/Dashboard/index.tsx
packages/website/src/routes/HomeMap/SiteTable/SelectedSiteCard/index.test.tsx
packages/website/src/routes/MonitoringRoutes/index.tsx
packages/website/src/routes/RegisterSite/index.tsx
packages/website/src/routes/SiteRoutes/Site/index.test.tsx
packages/website/src/routes/SiteRoutes/Site/index.tsx
packages/website/src/routes/SiteRoutes/SiteApplication/index.tsx
packages/website/src/routes/SiteRoutes/SurveyPoint/index.test.tsx
packages/website/src/routes/SiteRoutes/SurveyPoint/index.tsx
packages/website/src/routes/SiteRoutes/UploadData/index.tsx
packages/website/src/routes/SiteRoutes/index.test.tsx
packages/website/src/routes/SiteRoutes/index.tsx
packages/website/src/routes/Surveys/New/UploadMedia.tsx
packages/website/src/routes/Surveys/index.tsx
packages/website/src/routes/Uploads/index.tsx

fix #1019
fix #1020 
/claim #1019
/claim #1020
1. The major change is to update react-router to v6, a lot of breaking changes includes
2.  use link `[highlights.aqualink.org/learn-more/get-started-with-aqualink#h.49zi97uifdjf](https://highlights.aqualink.org/learn-more/get-started-with-aqualink#h.49zi97uifdjf)` for dashboard
3. Update util to sort Sonda data to display the latest upload

Update react router usage to v6; fix minor issue

---

packages/website/src/routes/Faq/__snapshots__/index.test.tsx.snap
packages/website/src/routes/Faq/index.tsx

Deleted all info about receiving free buoys. I added one section explaining that we're no longer donating. 
@ericboucher, can you please run Yarn for me?

Delete mention of "free buoys" in FAQ

---

packages/website/src/routes/HomeMap/SiteTable/SelectedSiteCard/index.tsx

Fix the link to selected site when there is no image

Fix sites link bug

---

packages/website/src/routes/HomeMap/Map/Markers/SiteMarker.tsx
packages/website/src/routes/HomeMap/Map/Markers/index.tsx
packages/website/src/routes/SiteRoutes/SiteApplication/Form/__snapshots__/index.test.tsx.snap
yarn.lock

Target: https://github.com/aqualinkorg/aqualink-app/pull/1069 map-performance
- Use CircleMarker for buoys to render marker on canvas which improves performance.
- Use Marker (which is rendered on DOM) for the rest of markers (minority).
- Remove filtering & clustering

Use circle marker for buoys

---

packages/website/src/common/SiteDetails/Surveys/ReefCheckSurveyCard/index.test.tsx
packages/website/src/common/SiteDetails/Surveys/ReefCheckSurveyCard/index.tsx
packages/website/src/common/SiteDetails/Waves/index.tsx
packages/website/src/routes/HomeMap/Map/index.tsx

Increase click tolerance on the map. This should help with clicks on touch screen

Increase map click tolerance

---

packages/website/src/common/Chart/index.tsx

Update chart memoization to fix chart not updating after date pick

Fix chart not updating after date pick

---

packages/website/src/routes/SiteRoutes/Site/SiteInfo/index.tsx

Update back button behavior

---

packages/website/src/routes/HomeMap/SiteTable/SelectedSiteCard/CardContent.tsx
packages/website/src/routes/SiteRoutes/Site/SiteInfo/EditForm/index.tsx

Update text color for site card on mobile

---

packages/website/src/common/SiteDetails/Surveys/ReefCheckSurveyCard/index.test.tsx
packages/website/src/common/SiteDetails/Surveys/ReefCheckSurveyCard/index.tsx
packages/website/src/routes/SiteRoutes/ReefCheckSurveys/ReefCheckSurveyDetails.tsx
packages/website/src/routes/SiteRoutes/ReefCheckSurveys/ReefCheckSurveySummary.tsx
packages/website/src/routes/SiteRoutes/ReefCheckSurveys/colDefs/reefStructure.colDef.ts
packages/website/src/routes/SiteRoutes/ReefCheckSurveys/index.test.tsx

Fixes #1103
- Divide composition items by 40
- Fix survey date formatting

Fix reef check issues

---

packages/api/ONBOARDING.md
packages/api/migration/1744966607999-RemoveUniqueConstraintFromReefCheckSiteSiteId.ts
packages/api/package.json
packages/api/scripts/reef-check.ts
packages/api/src/reef-check-sites/reef-check-sites.entity.ts
packages/api/src/reef-check-surveys/reef-check-surveys.controller.ts
packages/api/src/sites/sites.entity.ts
packages/api/src/sites/sites.service.ts
packages/api/src/utils/sofar.test.ts
packages/website/src/helpers/siteUtils.ts
packages/website/src/mocks/mockSite.ts
packages/website/src/routes/SiteRoutes/Site/index.tsx
packages/website/src/store/Sites/types.ts
yarn.lock

- Facilitate data updates
- Fix handling of large files
- Also fixes #1096 (upload surveys for merged sites)

Reef Check - Facilitate data updates and handling of large files

---

packages/website/src/common/SiteDetails/index.tsx

Fix missing spotter data

---

packages/api/package.json
packages/api/src/reef-check-surveys/reef-check-surveys.controller.ts
packages/api/src/reef-check-surveys/reef-check-surveys.service.ts
packages/website/src/routes/SiteRoutes/Site/index.tsx
packages/website/src/services/reefCheckService.ts
packages/website/src/store/ReefCheckSurveys/reefCheckSurveyListSlice.ts
yarn.lock

Fix survey links for reef check data
Rollback breaking next/common lib update

Fix survey links

---

packages/website/src/routes/Dashboard/Map/index.tsx
packages/website/src/routes/HomeMap/SiteTable/body.tsx
packages/website/src/routes/HomeMap/SiteTable/index.tsx
packages/website/src/routes/HomeMap/SiteTable/tableHead.tsx

- Default to sat map for collections
- Filter out empty buoy columns in collection site table

Improve collections

---

packages/website/src/routes/HomeMap/Map/InfoDialog/index.tsx
packages/website/src/routes/HomeMap/Map/alertLevelLegend.tsx
packages/website/src/routes/HomeMap/Map/index.tsx

Fix #1149
/claim #1149
https://github.com/user-attachments/assets/ff818587-9cc0-4c34-b01c-f65fecac4136

add map info dialog

---

packages/website/src/constants/collections.ts
packages/website/src/routes/Dashboard/index.tsx
packages/website/src/routes/Surveys/New/Map.tsx
packages/website/src/worker.ts

Hi Eric, 
I added some more collection names to make some prettier and more informative URLs. 
When running yarn test -u. I ran into some issues unrelated to these changes. See Slack for more info.

More Collection names
