package.json, packages/api/.eslintrc, packages/api/src/app.module.ts, packages/api/src/utils/temperature.test.ts, packages/api/src/utils/temperature.ts, packages/api/test/app.e2e-spec.ts
Slight update to the linting configuration. This makes `yarn lint:all` in the project root directory use lerna to run `yarn lint` in each sub repo rather than a single invocation with a "blob" operator from the root. Hopefully this will fix the ci linting errors.
=> Fix linting config

packages/api/src/reefs/daily-data.entity.ts, packages/api/src/reefs/reefs.entity.ts, packages/api/src/reefs/reefs.service.ts
This PR augments the `[GET] /reefs` endpoint to include the latest available daily data.
=> Augment get-reefs endpoint to include latest daily data

packages/website/src/helpers/numberUtils.ts, packages/website/src/routes/Homepage/Map/Popup/index.tsx, packages/website/src/routes/Homepage/ReefTable/SelectedReefCard/index.tsx, packages/website/src/routes/Homepage/ReefTable/__snapshots__/index.test.tsx.snap, packages/website/src/routes/Homepage/ReefTable/index.tsx, packages/website/src/routes/ReefRoutes/Reef/Charts/Tooltip/__snapshots__/index.test.tsx.snap, packages/website/src/routes/ReefRoutes/Reef/Charts/Tooltip/index.test.tsx, packages/website/src/routes/ReefRoutes/Reef/Charts/Tooltip/index.tsx, packages/website/src/routes/ReefRoutes/Reef/Satellite/index.tsx, packages/website/src/routes/ReefRoutes/Reef/Waves/index.tsx, packages/website/src/routes/ReefRoutes/Reef/Wind/index.tsx
Improving the formatNumber function utils to display `0` properly and `null || undefined` as `- -`.
=> Improve formatNumber function

packages/api/src/seeds/create-reefs.seeds.ts, packages/api/src/seeds/reefs-point-of-interest.factory.ts
Add Reef Point Of Interest factory.
- 4 ReefPointOfInterest entities are created and related to the previously created reef
- Name of reef is in format 'Mock Reef Point Of Interest {FameName}'
- No custom image is added
=> Seed Reef Point Of Interest

packages/website/src/common/NavBar/__snapshots__/index.test.tsx.snap, packages/website/src/common/NavBar/index.tsx, packages/website/src/routes/Homepage/Map/Popup/__snapshots__/index.test.tsx.snap, packages/website/src/routes/Homepage/Map/Popup/index.tsx, packages/website/src/routes/Homepage/ReefTable/SelectedReefCard/__snapshots__/index.test.tsx.snap, packages/website/src/routes/Homepage/ReefTable/SelectedReefCard/cardChart.tsx, packages/website/src/routes/Homepage/ReefTable/SelectedReefCard/index.tsx, packages/website/src/routes/Homepage/ReefTable/__snapshots__/index.test.tsx.snap, packages/website/src/routes/Homepage/ReefTable/index.tsx, packages/website/src/routes/Homepage/__snapshots__/index.test.tsx.snap, packages/website/src/routes/ReefRoutes/Reef/Satellite/__snapshots__/index.test.tsx.snap, packages/website/src/routes/ReefRoutes/Reef/Satellite/index.tsx, packages/website/src/routes/ReefRoutes/Reef/__snapshots__/index.test.tsx.snap
SelectedReefCard display improvements for web and mobile views.
The third image is from an iPad-sized screen - in this size range there are definite improvements to make still but all the content is at visible. Could consider using the mobile layout for this screen size?
=> Added mobile responsive design to SelectedReefCard

packages/api/cloud-functions/index.ts, packages/api/package.json, packages/api/scripts/daily-update.ts, packages/api/src/workers/dailyData.ts, yarn.lock
Attempts to speed up daily data updates by adding parallelism to the update process.
In local testing I saw 6-7 seconds per reef update with serial execution.
With 8 concurrent updates I was able to run updates on all 364 reefs in the staging DB in ~260 seconds.
=> Add parallelism to Cloud Function Updates

packages/website/src/routes/Homepage/Map/Popup/__snapshots__/index.test.tsx.snap, packages/website/src/routes/Homepage/Map/Popup/index.test.tsx, packages/website/src/routes/Homepage/Map/Popup/index.tsx, packages/website/src/routes/Homepage/Map/index.tsx, packages/website/src/routes/Homepage/Map/markers.tsx, packages/website/src/routes/Homepage/Map/sofarLayers.tsx
This PR improves the performance of the homepage map by eliminating unnecessary re-renders caused by state changing. This is primarily accomplished by refactoring the dependencies into separate components to ensure that any data changes only affect a small list of components.
The `reefOnMap`/active reef logic also was refactored to avoid rendering duplicate `Marker` components.
In testing this results in fairly smooth "flying" behavior. I see a noticeable difference in lag on my computer with dev tools open vs. dev tools closed, which is interesting. Slow internet can also cause some (likely unavoidable) jerkiness as tiles take a little bit to load. Hopefully this PR should improve the situation to acceptable levels though.
=> Improve Homepage Map Performance

packages/website/src/routes/Homepage/ReefTable/SelectedReefCard/__snapshots__/index.test.tsx.snap, packages/website/src/routes/Homepage/ReefTable/SelectedReefCard/index.test.tsx, packages/website/src/routes/Homepage/ReefTable/SelectedReefCard/index.tsx, packages/website/src/routes/Homepage/ReefTable/__snapshots__/index.test.tsx.snap, packages/website/src/routes/Homepage/ReefTable/body.tsx, packages/website/src/routes/Homepage/ReefTable/index.tsx, packages/website/src/routes/Homepage/ReefTable/tableHead.tsx, packages/website/src/routes/Homepage/ReefTable/types.ts, packages/website/src/routes/Homepage/ReefTable/utils.ts, packages/website/src/routes/Homepage/__snapshots__/index.test.tsx.snap, packages/website/src/routes/Homepage/index.tsx, packages/website/src/store/Homepage/types.ts, packages/website/src/store/Reefs/helpers.ts
This PR switches the reef table to Material UI's built-in table and separates different state dependencies to minimize reloading.
This PR replaces #149. It fixes #114.
=> Update reef table to use Material UI table

packages/website/src/routes/Homepage/Map/Markers/index.tsx
This PR fixes #180 by making sure that reef cards open on table click even if clustered.
=> Make marker pop-up open on table reef click

packages/website/src/store/User/userSlice.ts
The problem we have is that getSelf is called on `auth` change. But during sign-in, the auth change happens at the very beginning, and getSelf finishes before the signIn is over and the data from the signIn chunck ends up overriding the data we just got.
So as a hacky way to fix #222 I fetch all the data during the signIn chunck, similar to what we do during the create chunck.
There is probably a better way to handle this, so I am open to suggestions.
=> Hacky fix to get user data on sign-in

packages/website/src/layout/App/theme.ts, packages/website/src/routes/ReefRoutes/Reef/Waves/__snapshots__/index.test.tsx.snap, packages/website/src/routes/ReefRoutes/Reef/Waves/index.tsx
The purpose of this PR is to fix the appearance of bold text values. This issue has appeared on:
- "DHW" on homepage  map popup
- Reef detail page waves/wind card metrics values
=> Fix bold text

packages/website/src/common/Chart/ChartWithTooltip.tsx, packages/website/src/common/Chart/index.tsx, packages/website/src/common/Chart/utils.ts
=> Adapt date format for smaller charts

packages/api/src/surveys/surveys.service.ts, packages/website/src/routes/ReefRoutes/Reef/Surveys/DeleteButton.tsx
Proceed without stopping deletion process on survey deletion endpoint
Throw internal server error if failed to delete a survey media on survey media deletion endpoint
Add more logging on both endpoints
=> Catch failed media deletion when deleting a survey

packages/website/src/common/Chart/index.tsx, packages/website/src/routes/Homepage/ReefTable/SelectedReefCard/index.tsx, packages/website/src/routes/Homepage/ReefTable/__snapshots__/index.test.tsx.snap, packages/website/src/routes/Homepage/ReefTable/body.tsx, packages/website/src/routes/Homepage/ReefTable/index.tsx, packages/website/src/routes/Homepage/ReefTable/tableHead.tsx
- Add a spacing before the table and align card and text
- Switch to monthly ticks when the charts are smaller (width < 400)
=> Improve table card alignment and small charts

packages/api/src/reefs/dto/create-reef.dto.ts, packages/api/src/reefs/dto/update-reef.dto.ts, packages/api/src/reefs/reefs.controller.spec.ts, packages/api/src/reefs/reefs.controller.ts, packages/api/src/reefs/reefs.module.ts, packages/api/src/reefs/reefs.service.ts
Update reef endpoint:
- PUT /reefs/<reef_id> (Update reef)
Issue: The reefs admins were not updated properly
Fix: The endpoint accepts a User[] which are the active admins of the reef. If no value is provided no update actions on reefs admins is performed
- POST /reefs (Create reef)
Issue: The reefs admins were not added properly. Also regions, timezones and MMM were being provided by the client and not fetched via the reefs uits
Fix: Apply same flow as reef-application creation
=> Update reef endpoints

packages/website/src/routes/ReefRoutes/Reef/CoralBleaching/__snapshots__/index.test.tsx.snap, packages/website/src/routes/ReefRoutes/Reef/CoralBleaching/index.tsx, packages/website/src/routes/ReefRoutes/Reef/ReefDetails.tsx, packages/website/src/routes/ReefRoutes/Reef/Satellite/__snapshots__/index.test.tsx.snap, packages/website/src/routes/ReefRoutes/Reef/Satellite/index.tsx, packages/website/src/routes/ReefRoutes/Reef/Sensor/__snapshots__/index.test.tsx.snap, packages/website/src/routes/ReefRoutes/Reef/Sensor/index.tsx, packages/website/src/routes/ReefRoutes/Reef/Waves/__snapshots__/index.test.tsx.snap, packages/website/src/routes/ReefRoutes/Reef/Waves/index.tsx, packages/website/src/routes/ReefRoutes/Reef/styles.ts
The purpose of this PR is to add uniform spacing between the reef detail page cards. The design implemented looks like this:
=> Card uniform spacing

packages/api/src/reef-applications/reef-applications.service.ts, packages/api/src/reefs/reefs.service.ts, packages/api/src/utils/reef.utils.ts
Add error handler to recognize and send a more user-friendly message when a reef update/insert fails due to a unique violation on the polygon (location) field.
=> Handle duplicate reef location

packages/api/cloud-functions/index.ts
According to this guide https://firebase.google.com/docs/functions/schedule-functions we can add a crontab string to schedule the function with a custom period.
Also we can set the timezone which will be used to match the above filled pattern. (The default is America/Los_Angeles but we set it to be more verbose)
Related issue https://github.com/aqualinkorg/aqualink-app/issues/304
=> Run daily update at 4am PST

packages/website/src/routes/HomeMap/Map/Markers/index.tsx, packages/website/src/routes/HomeMap/Map/Popup/__snapshots__/index.test.tsx.snap, packages/website/src/routes/HomeMap/Map/Popup/index.test.tsx, packages/website/src/routes/HomeMap/Map/Popup/index.tsx
This PR is scheduled to fix the homepage map crashing issue. It basically removes the `ActiveReefListener` component, which used `leaflet`'s `"moveend"`, which seemed to cause the issue. This approach passes a `ref` to the selected reef's `Popup` and opens it via `popup.setLatLng([lat, lng]).openOn(map)`.
=> Remove `ActiveReefListener` component

packages/website/src/common/Chart/ChartWithTooltip.tsx, packages/website/src/routes/ReefRoutes/Reef/ReefDetails.tsx, packages/website/src/routes/ReefRoutes/Reef/index.tsx, packages/website/src/store/Reefs/selectedReefSlice.ts, packages/website/src/store/Reefs/types.ts
We noticed that when visiting a site with no spotter after visiting a site with a spotter, the spotter chart would sometimes stay on with data from the previous site.
This PR is adding an `hasSpotter` check before displaying spotter charts.
We could also look into making sure that `spotterData` get's removed properly when a new site is selected.
@tleraj let me know what you think
=> Hide spotter chart when site has no spotter

packages/website/.env.example, packages/website/src/common/Search/__snapshots__/index.test.tsx.snap, packages/website/src/common/Search/index.tsx, packages/website/src/routes/HomeMap/Map/index.tsx, packages/website/src/routes/HomeMap/ReefTable/body.tsx, packages/website/src/services/mapServices.ts, packages/website/src/store/Homepage/homepageSlice.ts, packages/website/src/store/Homepage/types.ts
This PR:
- adds the region name to the searchable text and display
- autoselects the first row so that clicking enter zooms on it
- if no site is found, propose to use geolocation on `enter`
=> Add autoselect and geolocation to search bar

packages/website/src/common/ErrorPage/__snapshots__/index.test.tsx.snap, packages/website/src/common/NavBar/index.tsx, packages/website/src/common/RegisterDialog/__snapshots__/index.test.tsx.snap, packages/website/src/common/RegisterDialog/index.tsx, packages/website/src/common/SignInDialog/__snapshots__/index.test.tsx.snap, packages/website/src/common/SignInDialog/index.tsx, packages/website/src/routes/Landing/__snapshots__/index.test.tsx.snap, packages/website/src/routes/ReefRoutes/Reef/__snapshots__/index.test.tsx.snap, packages/website/src/routes/Terms/__snapshots__/index.test.tsx.snap
Text update to help differentiate between account creation and site registration.
=> Change text from "register" to "sign up"

packages/website/src/routes/HomeMap/Map/Markers/index.tsx
The purpose of this PR is to fix the following bug:
Whenever we make a search on the homepage map and the click on a marker, the map centers to the search result again instead of centering into the marker.
=> Fix homepage map bug

packages/website/src/routes/ReefRoutes/Reef/index.tsx
Fixes #409 
test: http://aqua-bug.surge.sh
This bug can be replicated as follows:
1. On the map, pick any reef which has spotters.
2. Then, pick a reef which doesn't support spotters.
3. Before the new reef finishes loading, click explore
4. No Data Found
This happens because https://github.com/aqualinkorg/aqualink-app/blob/695fae2ceee75c7b5b7e552ee6a71b98afb95d33/packages/website/src/routes/ReefRoutes/Reef/index.tsx#L119 is calculated using the old reef, before the new reef gets a chance to load. In doing so, we end up requesting spotter data for a reef that doesn't support it, causing an error.
=> Fix No Data Found bug

packages/website/src/routes/HomeMap/Map/Markers/index.tsx, packages/website/src/routes/HomeMap/Map/Popup/index.tsx
Closes #426
Disables `Popup`'s auto opening `useEffect` if the marker its applied on isn't the original marker (its an offset)
test: http://aqua-popup.surge.sh
=> Fix popup closing issue

packages/website/src/common/Chart/Tooltip/index.tsx
=> Fix chart tooltip spacing

packages/website/src/common/NavBar/index.tsx, packages/website/src/common/Search/index.test.tsx, packages/website/src/common/Search/index.tsx, packages/website/src/routes/HomeMap/Map/Markers/index.tsx, packages/website/src/routes/HomeMap/Map/index.tsx, packages/website/src/routes/HomeMap/ReefTable/body.tsx, packages/website/src/routes/HomeMap/__snapshots__/index.test.tsx.snap, packages/website/src/routes/HomeMap/index.tsx, packages/website/src/routes/ReefRoutes/Reef/__snapshots__/index.test.tsx.snap, packages/website/src/routes/ReefRoutes/Reef/index.test.tsx, packages/website/src/routes/ReefRoutes/Reef/index.tsx, packages/website/src/routes/ReefRoutes/ReefsList/index.tsx, packages/website/src/routes/Surveys/index.tsx, packages/website/src/store/Reefs/reefsListSlice.ts, packages/website/src/store/Reefs/types.ts
The purpose of this PR is to close https://github.com/aqualinkorg/aqualink-app/issues/432. When the user is on site or survey details page and searches for a reef in the search bar, he gets redirected on the searched site's detail page.
Designs:
| desktop | mobile |
|---|---|
| ![Screenshot_20210201_152216](https://user-images.githubusercontent.com/64922890/106464467-601da580-64a1-11eb-9cde-f274d0d4a70b.png) | ![Screenshot_20210201_152202](https://user-images.githubusercontent.com/64922890/106464521-6b70d100-64a1-11eb-8403-1474012927ab.png) |
=> Add search bar to site and survey details pages

packages/website/src/routes/HomeMap/ReefTable/__snapshots__/index.test.tsx.snap, packages/website/src/routes/HomeMap/ReefTable/body.tsx, packages/website/src/routes/HomeMap/ReefTable/index.test.tsx, packages/website/src/routes/HomeMap/ReefTable/index.tsx, packages/website/src/routes/HomeMap/__snapshots__/index.test.tsx.snap, packages/website/src/routes/HomeMap/index.tsx
Test: http://aqua-drawer.surge.sh
This PR fixes a bug where the mobile drawer would scroll while closed causing a confusing overlay to show:
The mobile drawer now doesn't scroll at all, as any information the user needs would be at the top.
A bouncing pill animation was also added to encourage users to use the drawer after they selected a point on the map. The selected reef name is also shown at the bottom instead of 'all reefs'
=> Fix Mobile Drawer scrolling issues

packages/website/src/common/Chart/ChartWithCard/Chart.tsx, packages/website/src/common/Chart/ChartWithCard/helpers.ts, packages/website/src/common/Chart/ChartWithCard/index.tsx, packages/website/src/common/Chart/ChartWithTooltip.tsx, packages/website/src/common/Chart/utils.ts, packages/website/src/common/Datepicker/index.tsx, packages/website/src/helpers/dates.ts
The purpose of this PR is to fix the `HISTORIC` column hiding for small ranges issue.
The previous approach was looking for `maxMonthly` values in the range of `[pickerStartDate, pickerEndDate]`, and if it didn't find anything it returned nothing. Now, if no value exists to this interval, we return an array of the form:
```
[{pickerStartDate, valueClosestToStartDate}, ...filteredData, {pickerEndDate, valueClosestToEndDate}]
```
=> Show historic max line and values for small intervals

packages/website/src/helpers/reefUtils.ts, packages/website/src/routes/HomeMap/Map/Markers/index.tsx, packages/website/src/store/Reefs/reefsListSlice.ts
Noticed a bug on the markers that can be reproduced as follows:
- Turn on the `deployed buoys only` switch
- Select a site with spotter on the map
- Visit its details page
- Click the back button in order to return to the homepage
You can see several reefs on the map without deployed spotters (i.e. having the old marker)
=> Fix - re-filter spotters to "deployed" only

packages/website/src/common/SiteDetails/Surveys/SurveyCard/index.tsx
Noticed that we use the `!.` non-null-assertion operator in one place, which is error prone and causes the app to break in the very rare case that we get a survey with a user equal to `null`.
=> Remove non-null assertion operator

packages/website/src/common/ErrorPage/__snapshots__/index.test.tsx.snap, packages/website/src/common/NavBar/__snapshots__/index.test.tsx.snap, packages/website/src/common/NavBar/index.tsx, packages/website/src/routes/Landing/__snapshots__/index.test.tsx.snap, packages/website/src/routes/ReefRoutes/Reef/__snapshots__/index.test.tsx.snap, packages/website/src/routes/ReefRoutes/SurveyPoint/__snapshots__/index.test.tsx.snap, packages/website/src/routes/Terms/__snapshots__/index.test.tsx.snap
The purpose of this PR is to apply some new styles to the user dropdown menu on the navbar.
Styles added:
- Color change on hover
- Logout icon
- Divider between reefs and logout button
- Border color
- Change menu items padding
| before | after |
|---|---|
| ![Screenshot_20210412_021157](https://user-images.githubusercontent.com/64922890/114324887-7f861e00-9b35-11eb-93a9-c4e229f9efcd.png) | ![Screenshot_20210412_193600](https://user-images.githubusercontent.com/64922890/114429748-637e8d00-9bc6-11eb-91dc-4e6a71d49332.png) |
=> Change user dropdown menu styles

packages/api/package.json
Migrations will be run by default when we deploy to make sure that the API and db are in sync.
=> Warning - Add migration to deploy steps

packages/api/package.json
Addressing issue: https://github.com/aqualinkorg/aqualink-app/issues/527
Added two new scripts on `package.json`
- deploy:cloud-functions:programize
- deploy:cloud-functions:staging
=> Add cloud function deploy on both staging envs

packages/website/src/mocks/mockHoboDataRange.ts, packages/website/src/store/Reefs/helpers.ts, packages/website/src/store/Reefs/types.ts
In the #505 PR that was just merged the sensor data schema has changed a bit, which broke the frontend.
This is a first pass at fixing it but I think we should have a better structure for the sensor data in the frontend. Most of them will never have all these fields but simply a subset.
=> FIX - Update 'sofar_api' split in the frontend

packages/api/src/utils/liveData.ts, packages/api/src/workers/dailyData.ts, packages/api/src/workers/sstTimeSeries.ts
Because NOAA only publishes data one or two days late, the hourly update needs to look back more than 24 hours to find data to update with more certainty.
=> Extend backfill days for hourly SST updates

packages/api/src/reefs/reefs.service.ts, packages/api/src/time-series/latest-data.entity.ts, packages/api/src/utils/reef.utils.ts
Fallback to latest_data table for `SST` and `SST_ANOMALY`, if live data from Sofar does not contain the `satelliteTemperature` metric, in order to avoid null values.
=> Add fallback to latest_data table for live data

packages/website/src/routes/HomeMap/ReefTable/SelectedReefCard/__snapshots__/index.test.tsx.snap, packages/website/src/routes/HomeMap/ReefTable/SelectedReefCard/index.tsx, packages/website/src/routes/HomeMap/ReefTable/__snapshots__/index.test.tsx.snap, packages/website/src/routes/HomeMap/ReefTable/body.tsx, packages/website/src/routes/HomeMap/ReefTable/index.tsx, packages/website/src/routes/HomeMap/__snapshots__/index.test.tsx.snap, packages/website/src/routes/HomeMap/index.tsx
The purpose of this PR is to apply the mobile design of the `/map` page for screens < 960px.
Deployed [here](https://aqualink-app-programize.web.app/map).
Right now the designed is applied at < 600px which makes the iPad view a liitle squished.
Here's the difference of the previous and the current approach for iPad (768px):
| before | after |
|---|---|
| ![Screenshot_20210805_175012](https://user-images.githubusercontent.com/64922890/128371368-4e2b2c67-10d6-4275-b45c-347a1e5765b5.png) | ![Screenshot_20210805_175033](https://user-images.githubusercontent.com/64922890/128371404-b940432f-1865-457c-bc42-8c16ad8b7831.png) |
=> Set mobile design breakpoint at 960px for `/map`

packages/api/src/app.controller.ts
Ignore redirect endpoint GET /api on swagger API docs
=> Ignore redirect endpoint on api docs

packages/website/src/common/MenuDrawer/index.tsx, packages/website/src/routes/HomeMap/Map/Popup/index.tsx, packages/website/src/routes/HomeMap/ReefTable/SelectedReefCard/index.tsx, packages/website/src/routes/Landing/__snapshots__/index.test.tsx.snap, packages/website/src/routes/Landing/index.tsx, packages/website/src/utils/google-analytics.ts
The purpose of this PR is to close https://github.com/aqualinkorg/aqualink-app/issues/479.
We generate analytics for:
- `/` page button clicks
- `/map` page `"EXPLORE"` button clicks
- side menu button clicks
Deployed [here](https://aqualink-app-programize.web.app/map).
Analytics can be viewed [here](https://analytics.google.com/analytics/web/#/report-home/a163899403w281402098p248240479) (access needed).
=> Generate google analytics

packages/api/src/main.ts, packages/api/src/reef-applications/reef-application.spec.ts, packages/api/src/reef-applications/reef-applications.controller.ts, packages/api/src/reef-applications/reef-applications.module.ts, packages/api/src/reef-applications/reef-applications.service.ts, packages/api/test/test.service.ts
Delete:
- GET /reef-applications/:id : Gets application based on a hashId and the uid
- PUT /reef-applications/:id : Update reefApplication based on a hashId
Also there was a functionality that allowed users to edit some reef column through the above PUT endpoint. This is no longer available and thus deleted.
=> Delete deprecated reef-application endpoints

packages/api/src/utils/math.test.ts, packages/api/src/utils/math.ts, packages/api/src/utils/sofar.test.ts, packages/api/src/workers/dailyData.test.ts, packages/website/src/common/SiteDetails/Waves/__snapshots__/index.test.tsx.snap, packages/website/src/common/SiteDetails/Waves/index.tsx, packages/website/src/routes/SiteRoutes/Site/__snapshots__/index.test.tsx.snap
Following a conversation with Sofar, we realized that there had been a misunderstanding on conventions used to represent wave directions.
We are switching back to using the meteorological convention for all metrics.
=> Flip wave directions

packages/website/src/common/Chart/MultipleSensorsCharts/index.tsx
The purpose of this PR is to close https://github.com/aqualinkorg/aqualink-app/issues/652.
When providing an initial `start/end` date via url query params, a time series data request is being dispatched, with the following metrics:
```typescript
const DEFAULT_METRICS = [
"bottom_temperature",
"top_temperature",
"wind_speed",
"significant_wave_height",
];
```
This data is being cached, and the cache invalidation happens only when one from `start/end` dates is changed. However, the information of whether a site has sonde data comes only after the time series data range request is fulfilled, so when the flag `hasSondeData` changes, the 3rd `useEffect` on `/MultipleSensorsCharts/index.tsx` gets triggered again with the sonde metrics, but since the `start/end` dates have not changed, the cache …
=> Fix water sampling charts not being displayed on view upload button click

packages/api/migration/1642631169209-fixLatestDataMaterializedView.ts, packages/api/src/time-series/latest-data.entity.ts
If a site had multiple sources with the same type (eg. a spotter was replaced), we ended up with two data points for a few metrics.
This new MV query fixes it but is a bit slower. We should investigate how to speed things up eventually.
=> Fix issue with multiple source_id for latest_data

packages/website/src/routes/SiteRoutes/UploadData/HistoryTable.tsx
=> Data upload history table tweaks

packages/api/src/sensors/sensors.spec.ts, packages/api/src/time-series/time-series.spec.ts, packages/api/src/utils/time-series.utils.ts, packages/website/src/common/Chart/MultipleSensorsCharts/index.tsx, packages/website/src/common/SiteDetails/WaterSampling/__snapshots__/index.test.tsx.snap, packages/website/src/common/SiteDetails/WaterSampling/index.test.tsx, packages/website/src/common/SiteDetails/WaterSampling/index.tsx, packages/website/src/common/SiteDetails/index.tsx, packages/website/src/routes/SiteRoutes/Site/index.tsx, packages/website/src/store/Sites/helpers.ts, packages/website/src/store/Sites/types.ts
The purpose of this PR is to close https://github.com/aqualinkorg/aqualink-app/issues/638.
This PR is a prework for https://github.com/aqualinkorg/aqualink-app/issues/639.
If a source metric has no data, we simply do not return it instead of an empty array. Likewise, if we have a source with no data for each metric, then we do not return the source at all.
=> Do not return sources with no data

packages/website/src/store/Sites/helpers.ts
The purpose of this PR is to close https://github.com/aqualinkorg/aqualink-app/issues/671.
The previous approach was based on the assumption that only on of `start`, `end` can change at a time. Now, we have added a case where if they both change, then refetch the time series data and replace the time series data previously stored
=> Fix time intervals wrong calculation

packages/api/src/utils/site.utils.ts, packages/api/src/utils/spotter-time-series.ts
The purpose of this PR is to fix the following error that occured on the spotter data backfill function on firebase:
```
A firebase error has occurred on firebase function scheduledSpotterTimeSeriesUpdate:
TypeError: Cannot read properties of undefined (reading 'sensorId')
```
This error occurs because there might be spotters with no exclusion dates, thus the
```typescript
exclusionDatesRepository.find({ where: { sensorId: source.sensorId } })
```
will return `[]`.
With the following approach, if a spotter has no exclusion dates, we simply return its data, otherwise we exclude the data that should be excluded.
=> Fix firebase spotter backfill error

packages/api/src/collections/dto/collection-data.dto.ts, packages/api/src/sites/dto/live-data.dto.ts, packages/api/src/sites/sites.entity.ts, packages/api/src/sites/sites.service.ts, packages/api/src/users/users.entity.ts, packages/api/src/users/users.service.ts, packages/api/src/workers/dailyData.test.ts
While building the aqualink-sdk, we realized that the OpenAPI documentation was marking fields as required when they are not.
This is a first pass at resolving required fields mismatch
=> OpenAPI doc fixes - explicitly mark a few fields as optional

packages/website/src/store/Sites/selectedSiteSlice.ts, packages/website/src/store/Sites/types.ts
This PR closes https://github.com/aqualinkorg/aqualink-app/issues/710
This is adding a counter so only one request of live data can run at a time.
=> Make live data request run only once

packages/api/src/time-series/time-series.service.ts, packages/website/src/common/InfoWithAction/index.tsx, packages/website/src/common/StatusSnackbar/index.tsx, packages/website/src/routes/SiteRoutes/Site/index.tsx, packages/website/src/routes/SiteRoutes/UploadData/FileList.tsx, packages/website/src/routes/SiteRoutes/UploadData/Selectors.tsx, packages/website/src/routes/SiteRoutes/UploadData/UploadButton.tsx, packages/website/src/routes/SiteRoutes/UploadData/UploadWarnings.tsx, packages/website/src/routes/SiteRoutes/UploadData/index.tsx, packages/website/src/routes/SiteRoutes/index.tsx, packages/website/src/services/uploadServices.ts, packages/website/src/store/reducer.ts, packages/website/src/store/uploads/types.ts, packages/website/src/store/uploads/uploadsSlice.ts
The purpose of this PR is to resolve https://github.com/aqualinkorg/aqualink-app/issues/699
This PR moves all upload logic to a redux slice, making it possible for the user to browse the application while waiting for the upload to finish. It also fixes an issue of not all files being processed in the backend, if one failed, and keeping them in local file system
=> Run upload request in the background

packages/api/src/sites/sites.controller.ts, packages/api/src/sites/sites.service.ts, packages/api/src/workers/dailyData.ts, packages/website/src/common/Chart/MultipleSensorsCharts/DownloadCSVButton.tsx, packages/website/src/common/NavBar/index.tsx, packages/website/src/common/Search/index.tsx, packages/website/src/common/SiteDetails/Map/index.tsx, packages/website/src/common/SiteDetails/index.tsx, packages/website/src/routes/SiteRoutes/Site/SiteInfo/ExclusionDatesDialog/index.tsx, packages/website/src/routes/SiteRoutes/Site/index.tsx, packages/website/src/routes/SiteRoutes/SiteApplication/index.tsx, packages/website/src/routes/SiteRoutes/SurveyPoint/index.tsx, packages/website/src/routes/Surveys/index.tsx, packages/website/src/services/siteServices.ts, packages/website/src/store/Sites/selectedSiteSlice.ts, packages/website/src/store/Sites/types.ts
The purpose of this PR is to close https://github.com/aqualinkorg/aqualink-app/issues/711
This PR removes unnecessary FE request to `live_data` endpoint. It also creates a new `spotter_position` endpoint for getting the latest spotter coordinates and Deployed status.
=> Replace live_data request with spotter_position

packages/website/src/routes/Surveys/View/SurveyDetails.tsx, packages/website/src/routes/Surveys/View/utils.ts
Fixes #785 
Some of the data selectors we were using are not getting triggered properly so I switched to using site.dailyData instead.
And fall back to average values in dailyData when the spotter timeseries are not available.
https://aqualink.org/sites/2943/survey_details/401
=> Use site.dailyData for survey observation

packages/api/migration/1666786316691-AddNOAAAvailabilityColumn.ts, packages/api/package.json, packages/api/scripts/noaa-availability.ts, packages/api/src/sites/sites.entity.ts, packages/api/src/utils/liveData.ts, packages/api/src/utils/sofar-availability.test.ts, packages/api/src/utils/sofar-availability.ts, packages/api/src/utils/sst-time-series.ts, packages/api/src/workers/dailyData.ts, yarn.lock
This PR resolves https://github.com/aqualinkorg/aqualink-app/issues/784
- adds column `nearest_noaa_location` of type `geometry` to `sites` table
- adds script `yarn fill-noaa-nearest-point` to fill the above column at existing sites
Nearest available NOAA point is calculated, using netcdf files from https://coralreefwatch.noaa.gov/, which contain world wide data for single dates. Then running a breadth first search on the world 2x2 grid we calculate the nearest point.
This PR is a second attempt of it's [original](https://github.com/aqualinkorg/aqualink-app/pull/788), since we had issues deploying to cloud. It would be nice though if, in the future, we could automate the process instead of running the script manually.
=> Add nearest NOAA point column to sites and fill script

packages/api/migration/1667483794322-AddSpotterBottomPressure.ts, packages/api/scripts/noaa-availability.ts, packages/api/src/time-series/metrics.entity.ts, packages/api/src/utils/sofar.ts, packages/api/src/utils/sofar.types.ts, packages/api/src/utils/spotter-time-series.ts, packages/api/src/utils/uploads/upload-sheet-data.ts, packages/api/test/mock/daily-data.mock.ts, packages/website/src/common/Chart/MultipleSensorsCharts/index.tsx, packages/website/src/common/SiteDetails/Sensor/index.tsx, packages/website/src/store/Sites/helpers.ts, packages/website/src/store/Sites/types.ts
This PR resolves https://github.com/aqualinkorg/aqualink-app/issues/790
- adds new metric `barometric_pressure_bottom`
- renames metrics `barometric_pressure` and `barometric_pressure_diff` to `barometric_pressure_top` and `barometric_pressure_top_diff`
- adds bottom barometric pressure line graph if data are available
=> Add bottom pressure metric and line graphs

packages/api/src/sites/sites.service.ts, packages/website/src/routes/HomeMap/SiteTable/SelectedSiteCard/CardContent.tsx, packages/website/src/routes/HomeMap/SiteTable/SelectedSiteCard/__snapshots__/index.test.tsx.snap, packages/website/src/store/Sites/selectedSiteSlice.ts
This PR resolves https://github.com/aqualinkorg/aqualink-app/issues/776
Data in card where from `daily_data`, while in the table they are from `collectionData`, which in reality are `latest_data`.
To resolve the issue, we updated `sites/:id` endpoint to include the same `collectionData` as the `sites/` endpoint and use them instead of `daily_data`.
=> Fix featured card data do not match table data

.circleci/config.yml, packages/api/package.json, packages/api/scripts/comment-github.ts, packages/website/package.json, yarn.lock
This PR resolves https://github.com/aqualinkorg/aqualink-app/issues/741
Adds a CI step to Circle CI, which deploy the website to surge on every push. Also automatically comments  on the PR with the surge URL if the the deployment succeeds.
TODO: change `GH_USER` and `GH_TOKEN` in Circle CI env so it does not look like i make the comments.
=> Add deploy_website to ci actions

packages/api/src/collections/collections.controller.ts, packages/api/src/collections/collections.service.ts, packages/api/src/collections/collections.spec.ts, packages/api/src/collections/dto/create-collection.dto.ts, packages/api/src/users/users.service.ts, packages/api/src/utils/collections.utils.ts, packages/website/src/common/Banner/index.tsx, packages/website/src/helpers/siteUtils.ts, packages/website/src/helpers/user.ts, packages/website/src/routes/Dashboard/Content.tsx, packages/website/src/routes/Dashboard/index.tsx, packages/website/src/routes/SiteRoutes/Site/SiteInfo/CollectionButton/index.tsx, packages/website/src/routes/SiteRoutes/Site/SiteInfo/__snapshots__/index.test.tsx.snap, packages/website/src/routes/SiteRoutes/Site/__snapshots__/index.test.tsx.snap, packages/website/src/routes/Tracker/index.tsx, packages/website/src/services/collectionServices.ts, packages/website/src/store/Collection/collectionSlice.ts, packages/website/src/store/Collection/types.ts, packages/website/src/store/User/types.ts, packages/website/src/store/User/userSlice.ts
The purpose of this PR is to resolve https://github.com/aqualinkorg/aqualink-app/issues/802 and https://github.com/aqualinkorg/aqualink-app/issues/755
This PR fixes:
- [heat-stress](https://aqualink.org/collections/heat-stress) collection not being accessible
Changes: 
- Collections are created when a user tries to add their first site. This change does not affect the user's flow.
- Default collection name now is: "User Name's collection"
Adds:
- It is now possible to access public collection throw their id
- The [/tracker](https://aqualink.org/tracker) page is now also displayed when a user either has no collection or its empty with an extra banner
Additionally we can run the following SQL code to remove unused collections:
```
delete from collection c2
where c2.id not in  
(select c.id …
```
=> Improve Collections

packages/api/scripts/backfill-sofar-time-series.ts, packages/api/src/utils/spotter-time-series.ts, packages/api/src/utils/sst-time-series.ts, packages/api/src/workers/spotterTimeSeries.ts, packages/api/src/workers/sstTimeSeries.ts
The purpose of this PR is to solve an issue where not all sites would get SST updates daily from the functions.
We suspect that sofar API fails to answer the big amount of the functions' requests.
This PR combines the 4 per site requests to 1 per site, by combining the start and end API parameters.
It also cleans up the functions logs so they are more useful.
Also since the sofar hindcast gives only one value per day, we could reduce the `scheduledSSTTimeSeriesUpdate` function calls from 1 per hour to one per day.
=> Reduce number of requests in scheduledSSTTimeSeriesUpdate

packages/api/migration/1675934866004-AddEndOfLifeStatusTospotter.ts, packages/api/src/sites/sites.entity.ts
This PR resolves https://github.com/aqualinkorg/aqualink-app/issues/822
Adds a `end_of_life` spotter status enum option
=> Add end_of_life status for spotters

packages/website/src/common/Chip/index.tsx, packages/website/src/common/SiteDetails/CoralBleaching/__snapshots__/index.test.tsx.snap, packages/website/src/common/SiteDetails/HUICard/index.tsx, packages/website/src/common/SiteDetails/Satellite/__snapshots__/index.test.tsx.snap, packages/website/src/common/SiteDetails/Satellite/index.tsx, packages/website/src/common/SiteDetails/WaterSampling/__snapshots__/index.test.tsx.snap, packages/website/src/common/SiteDetails/WaterSampling/index.tsx, packages/website/src/common/SiteDetails/Waves/__snapshots__/index.test.tsx.snap, packages/website/src/common/SiteDetails/index.tsx, packages/website/src/common/UpdateInfo/__snapshots__/index.test.tsx.snap, packages/website/src/common/UpdateInfo/index.tsx, packages/website/src/common/types.ts, packages/website/src/layout/App/theme.ts, packages/website/src/store/Sites/types.ts, packages/website/src/utils/google-analytics.ts
This PR resolves https://github.com/aqualinkorg/aqualink-app/issues/801
Shows the following card, in the place of coral bleaching card, when HUI data are available. 
TODOs:
- Change value thresholds for metrics in HUI card with something meaningful
=> Add sampling card for HUI data

packages/api/migration/1680793520417-AddTimestampIndexToTimeSeries.ts, packages/api/src/time-series/time-series.entity.ts
Resolves https://github.com/aqualinkorg/aqualink-app/issues/786
Add index on `timestamp` on `time_series` table to speed up queries and `lates_data` refresh time.
=> Index "timestamp" column on "time_series" table

packages/api/src/collections/collections.spec.ts, packages/api/src/collections/dto/collection-data.dto.ts, packages/api/src/docs/api-sensor-data.ts, packages/api/src/sensors/dto/sensor-data.dto.ts, packages/api/src/sensors/sensors.service.ts, packages/api/src/time-series/metrics.entity.ts, packages/api/src/utils/collections.utils.ts, packages/api/src/utils/type-utils.ts, packages/website/src/store/Collection/utils.ts, packages/website/src/store/Sites/selectedSiteSlice.ts, packages/website/src/store/Sites/sitesListSlice.ts, packages/website/src/store/Sites/types.ts
The purpose of this PR is to resolve https://github.com/aqualinkorg/aqualink-app/issues/716
This PR aims to change all API case to camelCase.
In summary some API DTOs which were using `Metric` enum's raw values as keys, now use their camelCase equivalents.
=> Standardize API case

packages/api/package.json, packages/api/test/app.spec.ts, packages/api/test/global-setup.js, packages/api/test/jest.json, packages/api/test/test.service.ts
Resolves https://github.com/aqualinkorg/aqualink-app/issues/845
The timezone offset in both the actual nest app and the scripts is 0, but that is not the case in test. That was causing the tests to fail locally for anyone with no UTC time, while the app would appear to be working as expected. This change sets the timezone offset to 0 (UTC), for everyone, to match the nest app behavior.
=> Set timezone to UTC in tests

packages/website/src/common/SiteDetails/index.tsx
This PR updates the condition where the sonde `WaterSamplingCard` card appears.
Changes the condition from "there is `salinity` in latest data" to "at least n # of `sondeMetrics` are in latest data"
=> Update condition where sonde card appears 

.github/workflows/build_website.yml, packages/website/src/routes/Surveys/New/Map.tsx
resolves https://github.com/aqualinkorg/aqualink-app/issues/870
Replaces `::set-output` as stated here:
[github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
=> Replace deprecated ::set-output

packages/api/migration/1687182106885-AddSurfaceTemperatureMetric.ts, packages/api/src/sites/sites.service.ts, packages/api/src/time-series/metrics.enum.ts, packages/api/src/utils/constants.ts, packages/api/src/utils/sofar.test.ts, packages/api/src/utils/sofar.ts, packages/api/src/utils/sofar.types.ts, packages/api/src/utils/spotter-time-series.ts, packages/api/src/workers/dailyData.ts, packages/api/test/mock/daily-data.mock.ts, packages/website/src/common/Chart/MultipleSensorsCharts/index.tsx, packages/website/src/common/SiteDetails/Sensor/__snapshots__/index.test.tsx.snap, packages/website/src/common/SiteDetails/Sensor/index.tsx, packages/website/src/store/Sites/types.ts
resolves https://github.com/aqualinkorg/aqualink-app/issues/861
- adds `surface_temperature` metric
- swaps `sofarSensor` with the more light `sofarLatest`, when looking for spotter position 
- show spotter surface temperature to spotter card and add relative chart, if the metric is available
=> Add spotter surface_temperature

packages/api/scripts/upload-hobo-data.ts, packages/api/scripts/upload-hui-data.ts, packages/api/src/sites/sites.service.ts, packages/api/src/utils/uploads/upload-hobo-data.ts, packages/api/src/workers/backfill-site-data.ts, packages/api/test/utils.ts
resolves https://github.com/aqualinkorg/aqualink-app/issues/876
Cause of the issue was that a new database connection was attempting to be created, in `backfillSiteData`, from the the nest context, which already had it's own.
=> Fix new sites would not backfill daily data 

packages/api/migration/1689848494071-MakeTimeSeriesSourceNotNull.ts, packages/api/package.json, packages/api/src/time-series/time-series.entity.ts
This PR makes `survey_id` not NULL in `time-series` table.
`time-series` rows with NULL values for `survey_id` are meaningless for the application, since they can not be related to any site.
=> Make survey_id not null in time-series

packages/api/migration/1689588980336-AddQueryTimeout.ts, packages/api/package.json, packages/api/src/pipes/parse-metric-array.pipe.ts, packages/api/src/sensors/sensors.service.ts, packages/api/src/time-series/time-series.controller.ts, packages/api/src/time-series/time-series.service.ts, packages/api/src/time-series/time-series.spec.ts, packages/api/src/utils/time-series.utils.ts, packages/api/test/jest.json, packages/website/package.json, packages/website/src/common/Chart/MultipleSensorsCharts/DownloadCSVButton.tsx, packages/website/src/common/Chart/MultipleSensorsCharts/index.tsx, packages/website/src/custom.d.ts, packages/website/src/helpers/siteUtils.ts, packages/website/src/routes/SiteRoutes/UploadData/Header.tsx, packages/website/src/utils/utils.ts, yarn.lock
resolves https://github.com/aqualinkorg/aqualink-app/issues/879
Basically moves CSV creation to the backend, fixing the issue of missing date when selecting `all dates`.
The issue was caused because the backend limits time-series data to 3 months if no other limit is specified.
=> Fix missing data from CSV download

packages/api/src/sites/sites.service.ts, packages/api/src/utils/site.utils.ts
resolves https://github.com/aqualinkorg/aqualink-app/issues/937
In the case of new sites, if the `getGoogleRegion` function returned `undefined`, they would be automatically assigned to the first available region in the database.
=> Fix random region for new sites

packages/website/src/assets/caret.svg, packages/website/src/common/SiteDetails/CoralBleaching/__snapshots__/index.test.tsx.snap, packages/website/src/common/SiteDetails/Satellite/__snapshots__/index.test.tsx.snap, packages/website/src/common/SiteDetails/TemperatureChange/__snapshots__/index.test.tsx.snap, packages/website/src/common/SiteDetails/TemperatureChange/index.test.tsx, packages/website/src/common/SiteDetails/TemperatureChange/index.tsx, packages/website/src/common/SiteDetails/WaterSampling/__snapshots__/index.test.tsx.snap, packages/website/src/common/SiteDetails/Waves/__snapshots__/index.test.tsx.snap, packages/website/src/common/SiteDetails/index.tsx, packages/website/src/common/UpdateInfo/__snapshots__/index.test.tsx.snap, packages/website/src/common/UpdateInfo/index.tsx, packages/website/src/mocks/mockDailyData.ts, packages/website/src/routes/SiteRoutes/Site/__snapshots__/index.test.tsx.snap
Add 7-days temperature change card in place of Buoy Observation card when site doesn't have a spotter.
- Calculate the change based on `satelliteTemperature` from site's `dailyData`:  avg of 7 last days minus avg of 8-14 days back
- Calculate the avg temp of the last 7 days.
=> Add temperature change card in site dashboard

packages/website/README.md, packages/website/package.json
[Screencast from 03-12-2024 07:40:32 ΜΜ.webm](https://github.com/user-attachments/assets/7d0b7bb6-0e26-4df7-bebe-6cbfc9d8bbc0)
=> Add react-scan for performance profiling

.github/workflows/build_website.yml, packages/website/src/index.tsx
Fix routing for surge deployments (UI temp deployment for PR builds) by proving a 200.html as mentioned in the [docs](https://surge.sh/help/adding-a-200-page-for-client-side-routing).
We can now directly access specific pages and not only the home page (`/`)
-> https://aqualink-app-1079.surge.sh/sites/123
=> Add 200.html in surge deployment to fix routing

packages/api/migration/1738250706996-AddReefCheckSurveyCollectors.ts, packages/api/scripts/reef-check.ts, packages/api/src/reef-check-surveys/reef-check-surveys.entity.ts, packages/website/src/common/SiteDetails/CardWithTitle/index.tsx, packages/website/src/common/SiteDetails/Surveys/ReefCheckSurveyCard/index.test.tsx, packages/website/src/common/SiteDetails/Surveys/ReefCheckSurveyCard/index.tsx, packages/website/src/common/SiteDetails/Waves/index.tsx, packages/website/src/common/SiteDetails/index.tsx, packages/website/src/helpers/map.ts, packages/website/src/mocks/mockReefCheckSurvey.ts, packages/website/src/routes/HomeMap/Map/Markers/index.tsx, packages/website/src/routes/HomeMap/SiteTable/body.tsx, packages/website/src/routes/HomeMap/SiteTable/index.tsx, packages/website/src/store/ReefCheckSurveys/types.ts
- Add `teamLeader` and `teamScientist` columns in Reef Check Surveys
- Add script to upload these fields by parsing Data_collectors.xlsx
- Remove unused and potentially incorrect reef check stats command
Other small fixes:
- Fix video stream alignment. Closes #1089 
- Fix site table styles on mobile
- Fix `validateDOMNesting(...): <td> cannot appear as a child of <table>` console error
- Fix buoy animation origin
- Update wind direction icon size to match the text
- Fix site markers filtering
=> Add survey collectors fields

packages/website/src/routes/Landing/__snapshots__/index.test.tsx.snap, packages/website/src/routes/Landing/titles.ts
Hi Eric, 
We only need to change 500 to 6000 in the text on the home page. I tried a few things to get the yarn test -u working without success...
=> Change-500-to-6000
